import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Boxes,PackageCheck,Plus,Search,Settings,Shuffle,X} from 'lucide-react';
import AdministracaoSidebar from './AdministracaoSidebar';
import {api} from './services/api';
import './administracao-patrimonio.css';

const empty={numeroPatrimonial:'',descricao:'',categoria:'Equipamento',marcaModelo:'',numeroSerie:'',escolaId:'',setor:'',localizacao:'',responsavelId:'',estadoConservacao:'Bom',situacao:'Em uso',dataAquisicao:'',valor:'',comDivergencia:false,divergenciaDescricao:''};
const transferEmpty={novaEscolaId:'',novoSetor:'',novaLocalizacao:'',novoResponsavelId:'',motivo:''};
const date=value=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const money=value=>value==null?'Restrito':Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function AdministracaoPatrimonio({token,user,onLogout}){
 const [payload,setPayload]=useState({dados:[],resumo:{total:0,emUso:0,manutencao:0,divergencia:0},podeGerenciarValor:false});const [refs,setRefs]=useState({escolas:[],responsaveis:[]});const [form,setForm]=useState(empty);const [selected,setSelected]=useState(null);const [editing,setEditing]=useState(null);const [transfer,setTransfer]=useState(null);const [transferForm,setTransferForm]=useState(transferEmpty);const [transferStep,setTransferStep]=useState(1);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function load(selectedId=selected?.id){setLoading(true);setError('');try{const [assets,references]=await Promise.all([api.listAssets(token),api.listAssetReferences(token)]);setPayload(assets);setRefs(references);if(selectedId)setSelected(assets.dados.find(i=>i.id===selectedId)||null);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load(null);},[token]);
 const filtered=useMemo(()=>payload.dados.filter(i=>(!search||`${i.numeroPatrimonial} ${i.descricao} ${i.categoria} ${i.escola||''} ${i.setor||''}`.toLowerCase().includes(search.toLowerCase()))&&(!status||i.situacao===status)),[payload.dados,search,status]);
 function change(e){const {name,value,type,checked}=e.target;setForm(f=>({...f,[name]:type==='checkbox'?checked:value}));}
 function normalize(data){return {...data,escolaId:data.escolaId?Number(data.escolaId):null,responsavelId:data.responsavelId?Number(data.responsavelId):null,dataAquisicao:data.dataAquisicao||null,valor:payload.podeGerenciarValor&&data.valor!==''?Number(data.valor):null,marcaModelo:data.marcaModelo||null,numeroSerie:data.numeroSerie||null,setor:data.setor||null,divergenciaDescricao:data.divergenciaDescricao||null};}
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const result=editing?await api.updateAsset(editing,normalize(form),token):await api.createAsset(normalize(form),token);setMessage(result.message);setEditing(null);setForm(empty);await load();}catch(err){setError(err.message);}finally{setSaving(false);}}
 function startEdit(item){setEditing(item.id);setForm({...empty,...item,escolaId:item.escolaId||'',responsavelId:item.responsavelId||'',dataAquisicao:String(item.dataAquisicao||'').slice(0,10),valor:item.valor??''});setSelected(null);}
 function startTransfer(item){setTransfer(item);setTransferForm({...transferEmpty,novaLocalizacao:item.localizacao,novoResponsavelId:item.responsavelId||''});setTransferStep(1);setSelected(null);}
 async function confirmTransfer(){setSaving(true);setError('');try{const result=await api.transferAsset(transfer.id,{...transferForm,novaEscolaId:transferForm.novaEscolaId?Number(transferForm.novaEscolaId):null,novoResponsavelId:transferForm.novoResponsavelId?Number(transferForm.novoResponsavelId):null,novoSetor:transferForm.novoSetor||null},token);setMessage(result.message);setTransfer(null);await load();}catch(err){setError(err.message);}finally{setSaving(false);}}
 const metrics=[['Total de bens',payload.resumo.total,Boxes],['Em uso',payload.resumo.emUso,PackageCheck],['Em manutenção',payload.resumo.manutencao,Settings],['Com divergência',payload.resumo.divergencia,AlertTriangle]];
 return <div className="administration-shell"><AdministracaoSidebar user={user} onLogout={onLogout}/><main className="administration-main asset-page"><header className="administration-topbar"><div><small>SECRETARIA ADMINISTRATIVA &gt; OPERAÇÕES</small><h1>Patrimônio</h1><p>Gestão municipal de bens, localização, responsáveis e movimentações.</p></div><button className="asset-primary" onClick={()=>{setEditing(0);setForm(empty)}}><Plus/>Cadastrar bem</button></header><div className="asset-content">{error&&<p className="asset-feedback error">{error}</p>}{message&&<p className="asset-feedback success">{message}</p>}<section className="asset-metrics">{metrics.map(([label,value,Icon],index)=><article className={index===3?'warning':''} key={label}><Icon/><span><strong>{value}</strong><small>{label}</small></span></article>)}</section>
 <section className="asset-panel"><header><div><h2>Inventário municipal</h2><p>Bens cadastrados em toda a rede.</p></div><div className="asset-filters"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar patrimônio, descrição ou unidade"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas as situações</option>{['Em uso','Estoque','Manutenção','Transferência','Inservível','Baixado'].map(x=><option key={x}>{x}</option>)}</select></div></header>{loading?<div className="asset-empty">Carregando inventário…</div>:!filtered.length?<div className="asset-empty">Nenhum bem encontrado.</div>:<div className="asset-table"><table><thead><tr><th>Nº patrimonial</th><th>Descrição</th><th>Unidade/localização</th><th>Responsável</th><th>Conservação</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{filtered.map(item=><tr className={item.comDivergencia?'divergent':''} key={item.id}><td><b>{item.numeroPatrimonial}</b>{item.comDivergencia&&<small>Divergência</small>}</td><td><b>{item.descricao}</b><small>{item.categoria} · {item.marcaModelo||'Sem marca/modelo'}</small></td><td>{item.escola||item.setor}<small>{item.localizacao}</small></td><td>{item.responsavel||'Não definido'}</td><td>{item.estadoConservacao}</td><td><span className={`asset-status ${item.situacao.toLowerCase().replaceAll(' ','-')}`}>{item.situacao}</span></td><td><div className="asset-actions"><button onClick={()=>setSelected(item)}>Detalhes</button><button onClick={()=>startEdit(item)}>Editar</button><button className="transfer" onClick={()=>startTransfer(item)}><Shuffle/>Transferir</button></div></td></tr>)}</tbody></table></div>}</section>
 </div>
 {(editing!==null||form.numeroPatrimonial||form.descricao)&&<aside className="asset-drawer"><div className="asset-backdrop" onClick={()=>{setEditing(null);setForm(empty)}}/><form onSubmit={save}><header><div><small>{editing?'EDIÇÃO':'NOVO BEM'}</small><h2>{editing?'Editar patrimônio':'Cadastrar bem'}</h2></div><button type="button" onClick={()=>{setEditing(null);setForm(empty)}}><X/></button></header><div className="asset-form"><label>Número patrimonial<input name="numeroPatrimonial" value={form.numeroPatrimonial} onChange={change} required/></label><label>Descrição<input name="descricao" value={form.descricao} onChange={change} required/></label><div className="asset-grid"><label>Categoria<input name="categoria" value={form.categoria} onChange={change} required/></label><label>Marca/modelo<input name="marcaModelo" value={form.marcaModelo} onChange={change}/></label><label>Número de série<input name="numeroSerie" value={form.numeroSerie} onChange={change}/></label><label>Escola<select name="escolaId" value={form.escolaId} onChange={change}><option value="">Sem escola</option>{refs.escolas.map(x=><option value={x.id} key={x.id}>{x.nome}</option>)}</select></label><label>Setor<input name="setor" value={form.setor} onChange={change} placeholder="Quando não vinculado a escola"/></label><label>Localização<input name="localizacao" value={form.localizacao} onChange={change} required/></label><label>Responsável<select name="responsavelId" value={form.responsavelId} onChange={change}><option value="">Não definido</option>{refs.responsaveis.map(x=><option value={x.id} key={x.id}>{x.nome}</option>)}</select></label><label>Estado de conservação<select name="estadoConservacao" value={form.estadoConservacao} onChange={change}>{['Novo','Bom','Regular','Ruim','Inservível'].map(x=><option key={x}>{x}</option>)}</select></label><label>Situação<select name="situacao" value={form.situacao} onChange={change}>{['Em uso','Estoque','Manutenção','Transferência','Inservível','Baixado'].map(x=><option key={x}>{x}</option>)}</select></label><label>Data de aquisição<input type="date" name="dataAquisicao" value={form.dataAquisicao} onChange={change}/></label>{payload.podeGerenciarValor&&<label>Valor de aquisição<input type="number" min="0" step="0.01" name="valor" value={form.valor} onChange={change}/></label>}</div><label className="asset-checkbox"><input type="checkbox" name="comDivergencia" checked={form.comDivergencia} onChange={change}/> Bem com divergência</label>{form.comDivergencia&&<label>Descrição da divergência<textarea name="divergenciaDescricao" value={form.divergenciaDescricao} onChange={change} rows="3" required/></label>}</div><footer><button type="button" className="secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button><button disabled={saving}>{saving?'Salvando…':'Salvar bem'}</button></footer></form></aside>}
 {selected&&<aside className="asset-drawer"><div className="asset-backdrop" onClick={()=>setSelected(null)}/><section><header><div><small>{selected.numeroPatrimonial}</small><h2>{selected.descricao}</h2></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="asset-detail"><dl><div><dt>Categoria</dt><dd>{selected.categoria}</dd></div><div><dt>Marca/modelo</dt><dd>{selected.marcaModelo||'—'}</dd></div><div><dt>Número de série</dt><dd>{selected.numeroSerie||'—'}</dd></div><div><dt>Unidade</dt><dd>{selected.escola||selected.setor}</dd></div><div><dt>Localização</dt><dd>{selected.localizacao}</dd></div><div><dt>Responsável</dt><dd>{selected.responsavel||'—'}</dd></div><div><dt>Conservação</dt><dd>{selected.estadoConservacao}</dd></div><div><dt>Situação</dt><dd>{selected.situacao}</dd></div><div><dt>Aquisição</dt><dd>{date(selected.dataAquisicao)}</dd></div><div><dt>Valor</dt><dd>{money(selected.valor)}</dd></div></dl>{selected.comDivergencia&&<p className="asset-divergence"><AlertTriangle/> {selected.divergenciaDescricao||'Divergência não detalhada.'}</p>}<h3>Histórico completo</h3><div className="asset-history">{selected.historico.map(h=><article key={h.id}><b>{h.acao}</b><p>{h.descricao}</p><small>{h.usuario||'Sistema'} · {new Date(h.criadoEm).toLocaleString('pt-BR')}</small></article>)}</div></div></section></aside>}
 {transfer&&<aside className="asset-drawer"><div className="asset-backdrop" onClick={()=>setTransfer(null)}/><section><header><div><small>ETAPA {transferStep} DE 4</small><h2>Transferir {transfer.numeroPatrimonial}</h2></div><button onClick={()=>setTransfer(null)}><X/></button></header><div className="transfer-steps">{['Bem e origem','Nova unidade','Motivo e responsáveis','Confirmação'].map((x,i)=><span className={transferStep>=i+1?'active':''} key={x}><b>{i+1}</b>{x}</span>)}</div><div className="asset-form">{transferStep===1&&<div className="transfer-review"><h3>{transfer.descricao}</h3><p>Unidade atual: <b>{transfer.escola||transfer.setor}</b></p><p>Localização: <b>{transfer.localizacao}</b></p><p>Responsável: <b>{transfer.responsavel||'Não definido'}</b></p></div>}{transferStep===2&&<><label>Nova escola<select value={transferForm.novaEscolaId} onChange={e=>setTransferForm(f=>({...f,novaEscolaId:e.target.value}))}><option value="">Sem escola</option>{refs.escolas.map(x=><option value={x.id} key={x.id}>{x.nome}</option>)}</select></label><label>Novo setor<input value={transferForm.novoSetor} onChange={e=>setTransferForm(f=>({...f,novoSetor:e.target.value}))}/></label><label>Nova localização<input value={transferForm.novaLocalizacao} onChange={e=>setTransferForm(f=>({...f,novaLocalizacao:e.target.value}))} required/></label></>}{transferStep===3&&<><label>Motivo<textarea rows="4" value={transferForm.motivo} onChange={e=>setTransferForm(f=>({...f,motivo:e.target.value}))}/></label><label>Novo responsável<select value={transferForm.novoResponsavelId} onChange={e=>setTransferForm(f=>({...f,novoResponsavelId:e.target.value}))}><option value="">Não definido</option>{refs.responsaveis.map(x=><option value={x.id} key={x.id}>{x.nome}</option>)}</select></label></>}{transferStep===4&&<div className="transfer-review"><h3>Confirmar transferência</h3><p><b>Origem:</b> {transfer.escola||transfer.setor} · {transfer.localizacao}</p><p><b>Destino:</b> {refs.escolas.find(x=>String(x.id)===String(transferForm.novaEscolaId))?.nome||transferForm.novoSetor} · {transferForm.novaLocalizacao}</p><p><b>Motivo:</b> {transferForm.motivo}</p></div>}</div><footer>{transferStep>1&&<button className="secondary" onClick={()=>setTransferStep(x=>x-1)}>Voltar</button>}{transferStep<4?<button onClick={()=>{if(transferStep===2&&!transferForm.novaEscolaId&&!transferForm.novoSetor)return setError('Informe a nova unidade ou setor.');if(transferStep===3&&transferForm.motivo.trim().length<5)return setError('Informe o motivo da transferência.');setTransferStep(x=>x+1)}}>Continuar</button>:<button disabled={saving} onClick={confirmTransfer}>{saving?'Confirmando…':'Confirmar transferência'}</button>}</footer></section></aside>}
 </main></div>;
}
