import React,{useEffect,useMemo,useState} from 'react';
import {Archive,CheckCircle2,Clock3,FileText,Forward,Inbox,Plus,Search,Send,X} from 'lucide-react';
import AdministracaoSidebar from './AdministracaoSidebar';
import {api} from './services/api';
import './administracao-protocolo.css';

const empty={tipo:'Ofício',assunto:'',descricao:'',origem:'',prazo:''};
const actionFor={Recebido:['classificar','Classificar documento'],Encaminhado:['receber_setor','Registrar recebimento no setor'],'Em setor':['responder','Registrar resposta'],Respondido:['finalizar','Finalizar protocolo'],Finalizado:['arquivar','Arquivar protocolo']};
export default function AdministracaoProtocolo({token,user,onLogout}){
 const [payload,setPayload]=useState({dados:[],resumo:{}});const [refs,setRefs]=useState({responsaveis:[]});const [form,setForm]=useState(empty);const [selected,setSelected]=useState(null);const [action,setAction]=useState({classificacao:'',destinatario:'',setorDestino:'',responsavelId:'',prazo:'',despacho:''});const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function load(id=selected?.id){setLoading(true);try{const [protocols,references]=await Promise.all([api.listProtocols(token),api.getProtocolReferences(token)]);setPayload(protocols);setRefs(references);if(id)setSelected(protocols.dados.find(item=>item.id===id)||null);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load(null);},[token]);
 const filtered=useMemo(()=>payload.dados.filter(item=>(!status||item.status===status)&&(!search||`${item.numero} ${item.tipo} ${item.assunto} ${item.origem} ${item.destinatario||''}`.toLowerCase().includes(search.toLowerCase()))),[payload.dados,status,search]);
 async function save(event){event.preventDefault();setSaving(true);setError('');try{const result=await api.createProtocol({...form,prazo:form.prazo||null},token);setMessage(`${result.message} Número ${result.numero}.`);setForm(empty);setOpen(false);await load(null);}catch(e){setError(e.message);}finally{setSaving(false);}}
 function select(item){setSelected(item);setAction({classificacao:item.classificacao||'',destinatario:item.destinatario||'',setorDestino:item.setorAtual||'',responsavelId:item.responsavelId||'',prazo:String(item.prazo||'').slice(0,10),despacho:''});}
 async function execute(override){const current=override||actionFor[selected.status]?.[0];if(!current)return;setSaving(true);setError('');try{const data={acao:current,classificacao:action.classificacao||null,destinatario:action.destinatario||null,setorDestino:action.setorDestino||null,responsavelId:action.responsavelId?Number(action.responsavelId):null,prazo:action.prazo||null,despacho:action.despacho||actionFor[selected.status]?.[1]||'Tramitação registrada.'};const result=await api.actOnProtocol(selected.id,data,token);setMessage(result.message);setAction(value=>({...value,despacho:''}));await load(selected.id);}catch(e){setError(e.message);}finally{setSaving(false);}}
 const metrics=[['Protocolos registrados',payload.resumo.registrados||0,FileText],['Em tramitação',payload.resumo.emTramitacao||0,Clock3],['Aguardando resposta',payload.resumo.aguardandoResposta||0,Inbox],['Finalizados/arquivados',payload.resumo.finalizados||0,Archive]];
 return <div className="administration-shell"><AdministracaoSidebar user={user} onLogout={onLogout}/><main className="protocol-main"><header className="administration-topbar"><div><small>SECRETARIA ADMINISTRATIVA &gt; ADMINISTRATIVO</small><h1>Documentos e Protocolo</h1><p>Registro digital e histórico permanente de tramitação administrativa.</p></div><button className="protocol-primary" onClick={()=>setOpen(true)}><Plus/>Novo protocolo</button></header><div className="protocol-content">{error&&<p className="protocol-feedback error">{error}</p>}{message&&<p className="protocol-feedback success">{message}</p>}<section className="protocol-metrics">{metrics.map(([label,value,Icon])=><article key={label}><Icon/><span><strong>{value}</strong><small>{label}</small></span></article>)}</section><section className="protocol-panel"><header><div><h2>Registros administrativos</h2><p>Nenhum protocolo ou histórico pode ser apagado.</p></div><div className="protocol-filters"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar número, assunto ou origem"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option>{['Recebido','Encaminhado','Em setor','Respondido','Finalizado','Arquivado'].map(item=><option key={item}>{item}</option>)}</select></div></header>{loading?<p className="protocol-empty">Carregando…</p>:<div className="protocol-table"><table><thead><tr><th>Protocolo</th><th>Tipo e assunto</th><th>Origem</th><th>Destinatário/setor</th><th>Responsável</th><th>Prazo</th><th>Status</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} onClick={()=>select(item)}><td><b>{item.numero}</b><small>{new Date(item.criadoEm).toLocaleDateString('pt-BR')}</small></td><td><b>{item.tipo}</b><small>{item.assunto}</small></td><td>{item.origem}</td><td>{item.destinatario||'A classificar'}<small>{item.setorAtual||'Sem setor'}</small></td><td>{item.responsavel||'A definir'}</td><td>{item.prazo?new Date(`${String(item.prazo).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td><span className={`protocol-status ps-${item.status.toLowerCase().replaceAll(' ','-')}`}>{item.status}</span></td></tr>)}</tbody></table>{!filtered.length&&<p className="protocol-empty">Nenhum protocolo encontrado.</p>}</div>}</section></div>
 {open&&<div className="protocol-modal"><div className="protocol-backdrop" onClick={()=>setOpen(false)}/><form onSubmit={save}><header><div><small>REGISTRAR DOCUMENTO</small><h2>Novo protocolo</h2><p>O número será gerado automaticamente.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></header><div className="protocol-form"><div className="protocol-grid"><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}>{['Ofício','Memorando','Circular','Requerimento','Processo','Comunicação interna','Outros'].map(item=><option key={item}>{item}</option>)}</select></label><label>Origem<input required value={form.origem} onChange={e=>setForm({...form,origem:e.target.value})} placeholder="Unidade, setor ou pessoa"/></label></div><label>Assunto<input required value={form.assunto} onChange={e=>setForm({...form,assunto:e.target.value})}/></label><label>Descrição<textarea required rows="6" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label>Prazo inicial<input type="date" value={form.prazo} onChange={e=>setForm({...form,prazo:e.target.value})}/></label></div><footer><button disabled={saving}>{saving?'Registrando…':'Registrar e gerar protocolo'}</button></footer></form></div>}
 {selected&&<aside className="protocol-drawer"><div className="protocol-backdrop" onClick={()=>setSelected(null)}/><section><header><div><small>{selected.numero}</small><h2>{selected.assunto}</h2><span className="protocol-status">{selected.status}</span></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="protocol-detail"><p><b>{selected.tipo}</b> · origem: {selected.origem}</p><p>{selected.descricao}</p>{actionFor[selected.status]&&<section className="protocol-action"><h3>{actionFor[selected.status][1]}</h3>{selected.status==='Recebido'&&<label>Classificação<input value={action.classificacao} onChange={e=>setAction({...action,classificacao:e.target.value})} placeholder="Ex.: Administrativo, RH, Patrimônio"/></label>}{selected.status==='Encaminhado'&&<label>Responsável<select value={action.responsavelId} onChange={e=>setAction({...action,responsavelId:e.target.value})}><option value="">Selecione</option>{refs.responsaveis.map(item=><option value={item.id} key={item.id}>{item.nome} · {item.perfil}</option>)}</select></label>}{selected.status==='Recebido'&&selected.classificacao&&<><label>Destinatário<input value={action.destinatario} onChange={e=>setAction({...action,destinatario:e.target.value})}/></label><label>Setor de destino<input value={action.setorDestino} onChange={e=>setAction({...action,setorDestino:e.target.value})}/></label></>}<label>Prazo<input type="date" value={action.prazo} onChange={e=>setAction({...action,prazo:e.target.value})}/></label><label>Despacho<textarea rows="3" value={action.despacho} onChange={e=>setAction({...action,despacho:e.target.value})}/></label><div>{selected.status==='Recebido'&&!selected.classificacao?<button disabled={saving} onClick={()=>execute('classificar')}><CheckCircle2/>Classificar</button>:selected.status==='Recebido'?<button disabled={saving} onClick={()=>execute('encaminhar')}><Send/>Encaminhar</button>:<button disabled={saving} onClick={()=>execute()}>{selected.status==='Finalizado'?<Archive/>:<Forward/>}{actionFor[selected.status][1]}</button>}</div></section>}<h3>Timeline de tramitação</h3><div className="protocol-timeline">{selected.timeline.map((item,index)=><article key={item.id}><span>{index+1}</span><div><b>{item.evento} · {item.statusNovo}</b><p>{item.despacho}</p><small>{item.usuario||'Sistema'} · {new Date(item.criadoEm).toLocaleString('pt-BR')}{item.setorDestino?` · ${item.setorDestino}`:''}</small></div></article>)}</div></div></section></aside>}</main></div>;
}
