import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Clock3,Paperclip,Plus,Search,Settings,Upload,X} from 'lucide-react';
import AdministracaoSidebar from './AdministracaoSidebar';
import {api} from './services/api';
import './administracao-manutencao.css';

const empty={origem:'Escola',escolaId:'',bemId:'',veiculoId:'',itemLocal:'',problema:'',prioridade:'Normal',prazo:'',custo:'',anexo:null};
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file);});
const actions={Solicitação:['triar','Fazer triagem'],Triagem:['atribuir','Definir responsável'],Atribuída:['iniciar','Iniciar execução'],'Em execução':['comprovar','Enviar comprovação'],'Aguardando comprovação':['concluir','Concluir ordem']};
export default function AdministracaoManutencao({token,user,onLogout}){
 const [payload,setPayload]=useState({dados:[],resumo:{},podeGerenciarCusto:false});const [refs,setRefs]=useState({escolas:[],bens:[],veiculos:[],responsaveis:[]});const [form,setForm]=useState(empty);const [selected,setSelected]=useState(null);const [action,setAction]=useState({responsavelId:'',prazo:'',custo:'',descricao:'',anexo:null});const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function load(id=selected?.id){setLoading(true);try{const [orders,references]=await Promise.all([api.listMaintenance(token),api.getMaintenanceReferences(token)]);setPayload(orders);setRefs(references);if(id)setSelected(orders.dados.find(item=>item.id===id)||null);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load(null);},[token]);
 const filtered=useMemo(()=>payload.dados.filter(item=>(!status||item.status===status)&&(!search||`${item.protocolo} ${item.itemLocal} ${item.problema} ${item.escola||''}`.toLowerCase().includes(search.toLowerCase()))),[payload.dados,status,search]);
 async function chooseFile(event,target,etapa){const file=event.target.files?.[0];if(!file)return;if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){event.target.value='';return setError('Envie PDF, JPG, PNG ou WebP com no máximo 5 MB.');}try{const dados=await readFile(file);target(current=>({...current,anexo:{nome:file.name,dados,etapa}}));setError('');}catch(e){setError(e.message);}}
 async function save(event){event.preventDefault();setSaving(true);setError('');try{const data={...form,escolaId:form.escolaId?Number(form.escolaId):null,bemId:form.bemId?Number(form.bemId):null,veiculoId:form.veiculoId?Number(form.veiculoId):null,prazo:form.prazo||null,custo:payload.podeGerenciarCusto&&form.custo!==''?Number(form.custo):null};const result=await api.createMaintenance(data,token);setMessage(`${result.message} Protocolo ${result.protocolo}.`);setForm(empty);setOpen(false);await load(null);}catch(e){setError(e.message);}finally{setSaving(false);}}
 function select(item){setSelected(item);setAction({responsavelId:item.responsavelId||'',prazo:String(item.prazo||'').slice(0,10),custo:item.custo??'',descricao:'',anexo:null});}
 async function execute(){const config=actions[selected.status];if(!config)return;setSaving(true);setError('');try{const data={acao:config[0],responsavelId:action.responsavelId?Number(action.responsavelId):null,prazo:action.prazo||null,custo:payload.podeGerenciarCusto&&action.custo!==''?Number(action.custo):null,descricao:action.descricao||config[1],anexo:action.anexo};const result=await api.actOnMaintenance(selected.id,data,token);setMessage(result.message);setAction(current=>({...current,descricao:'',anexo:null}));await load(selected.id);}catch(e){setError(e.message);}finally{setSaving(false);}}
 const metrics=[['Ordens abertas',payload.resumo.abertas||0,Settings],['Urgentes',payload.resumo.urgentes||0,AlertTriangle],['Em execução',payload.resumo.execucao||0,Clock3],['Atrasadas',payload.resumo.atrasadas||0,AlertTriangle]];
 return <div className="administration-shell"><AdministracaoSidebar user={user} onLogout={onLogout}/><main className="maintenance-main"><header className="administration-topbar"><div><small>SECRETARIA ADMINISTRATIVA &gt; OPERAÇÕES</small><h1>Manutenção</h1><p>Triagem, execução e comprovação de serviços em toda a rede.</p></div><button className="maintenance-primary" onClick={()=>setOpen(true)}><Plus/>Nova ordem</button></header><div className="maintenance-content">{error&&<p className="maintenance-feedback error">{error}</p>}{message&&<p className="maintenance-feedback success">{message}</p>}<section className="maintenance-metrics">{metrics.map(([label,value,Icon],i)=><article className={(i===1||i===3)&&value?'warning':''} key={label}><Icon/><span><strong>{value}</strong><small>{label}</small></span></article>)}</section><section className="maintenance-panel"><header><div><h2>Ordens de manutenção</h2><p>Fluxo central de escolas, equipamentos, patrimônio e veículos.</p></div><div className="maintenance-filters"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar protocolo, item ou problema"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option>{Object.keys(actions).map(item=><option key={item}>{item}</option>)}<option>Concluída</option></select></div></header>{loading?<p className="maintenance-empty">Carregando…</p>:<div className="maintenance-table"><table><thead><tr><th>Protocolo/origem</th><th>Unidade e item</th><th>Problema</th><th>Prioridade</th><th>Responsável</th><th>Prazo</th><th>Status</th></tr></thead><tbody>{filtered.map(item=><tr onClick={()=>select(item)} key={item.id}><td><b>{item.protocolo}</b><small>{item.origem}</small></td><td><b>{item.escola||item.veiculo||item.numeroPatrimonial||'Rede municipal'}</b><small>{item.itemLocal}</small></td><td>{item.problema}</td><td><span className={`priority p-${item.prioridade.toLowerCase()}`}>{item.prioridade}</span></td><td>{item.responsavel||'A definir'}</td><td>{item.prazo?new Date(`${String(item.prazo).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td><span className="maintenance-status">{item.status}</span></td></tr>)}</tbody></table>{!filtered.length&&<p className="maintenance-empty">Nenhuma ordem encontrada.</p>}</div>}</section></div>
 {open&&<div className="maintenance-modal"><div className="maintenance-backdrop" onClick={()=>setOpen(false)}/><form onSubmit={save}><header><div><small>NOVA SOLICITAÇÃO</small><h2>Abrir ordem de manutenção</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></header><div className="maintenance-form"><div className="maintenance-grid"><label>Origem<select value={form.origem} onChange={e=>setForm({...form,origem:e.target.value})}>{['Escola','Equipamento','Patrimônio','Veículo'].map(item=><option key={item}>{item}</option>)}</select></label><label>Unidade<select value={form.escolaId} onChange={e=>setForm({...form,escolaId:e.target.value})}><option value="">Rede/Setor central</option>{refs.escolas.map(item=><option value={item.id} key={item.id}>{item.nome}</option>)}</select></label>{form.origem==='Patrimônio'&&<label>Bem patrimonial<select required value={form.bemId} onChange={e=>setForm({...form,bemId:e.target.value})}><option value="">Selecione</option>{refs.bens.map(item=><option value={item.id} key={item.id}>{item.numeroPatrimonial} · {item.descricao}</option>)}</select></label>}{form.origem==='Veículo'&&<label>Veículo<select required value={form.veiculoId} onChange={e=>setForm({...form,veiculoId:e.target.value})}><option value="">Selecione</option>{refs.veiculos.map(item=><option value={item.id} key={item.id}>{item.prefixo} · {item.placa}</option>)}</select></label>}<label>Item ou local<input required value={form.itemLocal} onChange={e=>setForm({...form,itemLocal:e.target.value})}/></label><label>Prioridade<select value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})}>{['Baixa','Normal','Alta','Urgente'].map(item=><option key={item}>{item}</option>)}</select></label><label>Prazo inicial<input type="date" value={form.prazo} onChange={e=>setForm({...form,prazo:e.target.value})}/></label>{payload.podeGerenciarCusto&&<label>Custo estimado<input type="number" min="0" step="0.01" value={form.custo} onChange={e=>setForm({...form,custo:e.target.value})}/></label>}</div><label>Problema<textarea rows="5" required value={form.problema} onChange={e=>setForm({...form,problema:e.target.value})}/></label><label className="maintenance-upload"><Upload/><span><b>Foto antes ou anexo</b><small>{form.anexo?.nome||'PDF, JPG, PNG ou WebP · até 5 MB'}</small></span><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>chooseFile(e,setForm,'Antes')}/></label></div><footer><button disabled={saving}>{saving?'Salvando…':'Criar ordem'}</button></footer></form></div>}
 {selected&&<aside className="maintenance-drawer"><div className="maintenance-backdrop" onClick={()=>setSelected(null)}/><section><header><div><small>{selected.protocolo}</small><h2>{selected.itemLocal}</h2><span className="maintenance-status">{selected.status}</span></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="maintenance-detail"><p><b>Origem:</b> {selected.origem} · {selected.escola||selected.veiculo||'Rede municipal'}</p><p><b>Problema:</b> {selected.problema}</p><p><b>Prioridade:</b> {selected.prioridade}</p>{selected.anexos.length>0&&<><h3>Anexos e fotos</h3><div className="maintenance-files">{selected.anexos.map(file=><button key={file.id} onClick={()=>api.downloadMaintenanceAttachment(selected.id,file,token)}><Paperclip/>{file.etapa} · {file.nome}</button>)}</div></>} {actions[selected.status]&&<section className="maintenance-action"><h3>{actions[selected.status][1]}</h3>{selected.status==='Triagem'&&<label>Responsável<select value={action.responsavelId} onChange={e=>setAction({...action,responsavelId:e.target.value})}><option value="">Selecione</option>{refs.responsaveis.map(item=><option value={item.id} key={item.id}>{item.nome} · {item.perfil}</option>)}</select></label>}<div className="maintenance-grid"><label>Prazo<input type="date" value={action.prazo} onChange={e=>setAction({...action,prazo:e.target.value})}/></label>{payload.podeGerenciarCusto&&<label>Custo<input type="number" min="0" step="0.01" value={action.custo} onChange={e=>setAction({...action,custo:e.target.value})}/></label>}</div><label>Despacho<textarea rows="3" value={action.descricao} onChange={e=>setAction({...action,descricao:e.target.value})}/></label>{selected.status==='Em execução'&&<label className="maintenance-upload"><Upload/><span><b>Foto depois ou comprovação</b><small>{action.anexo?.nome||'Anexo obrigatório nesta etapa'}</small></span><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>chooseFile(e,setAction,'Comprovação')}/></label>}<button disabled={saving} onClick={execute}><CheckCircle2/>{actions[selected.status][1]}</button></section>}<h3>Histórico</h3>{selected.historico.map(item=><article className="maintenance-history" key={item.id}><b>{item.statusNovo}</b><p>{item.descricao}</p><small>{item.usuario||'Sistema'} · {new Date(item.criadoEm).toLocaleString('pt-BR')}</small></article>)}</div></section></aside>}</main></div>;
}
