import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, FileBarChart, Pencil, Plus, Search, UsersRound, X } from 'lucide-react';
import AdministracaoSidebar from './AdministracaoSidebar';
import { api } from './services/api';
import './administracao-afastamentos.css';
import './administracao-afastamentos-enhancements.css';

const typeLabels={ferias:'Férias',licenca_medica:'Atestado médico',capacitacao:'Curso de aperfeiçoamento'};
const emptyForm={usuarioId:'',categoria:'ferias',tipo:'ferias',dataInicio:'',dataFim:'',retornoPrevisto:'',motivo:'',documento:null,documentoNome:''};
const readFile=(file)=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Não foi possível ler o documento.'));reader.readAsDataURL(file);});
const date=(value)=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const iso=(value)=>String(value||'').slice(0,10);
const days=(start,end)=>start&&end?Math.floor((new Date(`${end}T12:00:00`)-new Date(`${start}T12:00:00`))/86400000)+1:0;
const nextDay=(value)=>{if(!value)return '';const result=new Date(`${value}T12:00:00`);result.setDate(result.getDate()+1);return result.toISOString().slice(0,10);};

export default function AdministracaoAfastamentos({token,user,onLogout}){
  const [data,setData]=useState({dados:[],resumo:{emFerias:0,afastados:0,retornosProximos:0,pendencias:0},alertas:[],alertasAtestadosLongos:[]});
  const [employees,setEmployees]=useState([]);const [form,setForm]=useState(emptyForm);const [editingId,setEditingId]=useState(null);const [step,setStep]=useState(1);const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const fileInput=useRef(null);
  async function load(){setLoading(true);setError('');try{const [leaves,users]=await Promise.all([api.listPersonnelLeaves(token),api.listUsers(token)]);setData({...leaves,alertasAtestadosLongos:leaves.alertasAtestadosLongos||[]});setEmployees((Array.isArray(users)?users:users.dados||[]).filter(item=>Number(item.nivel)>3&&item.situacaoFuncional!=='desligado'));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[token]);
  const filtered=useMemo(()=>data.dados.filter(item=>(!search||`${item.nome} ${item.matricula||''} ${item.escola} ${typeLabels[item.tipo]||item.tipo}`.toLowerCase().includes(search.toLowerCase()))&&(!status||item.situacao===status)),[data.dados,search,status]);
  const periodDays=days(form.dataInicio,form.dataFim);const longMedical=form.tipo==='licenca_medica'&&periodDays>30;
  function change(event){const {name,value}=event.target;setForm(current=>{if(name==='categoria')return {...current,categoria:value,tipo:value==='ferias'?'ferias':'licenca_medica'};if(name==='dataFim')return {...current,dataFim:value,retornoPrevisto:nextDay(value)};return {...current,[name]:value};});setError('');}
  function next(){if(step===1&&!form.usuarioId)return setError('Selecione um funcionário.');if(step===2&&(!form.dataInicio||!form.dataFim||!form.retornoPrevisto))return setError('Informe o período e o retorno previsto.');if(step===2&&form.dataFim<form.dataInicio)return setError('A data final não pode ser anterior ao início.');if(step===3&&form.motivo.trim().length<5)return setError('Descreva o motivo do registro.');if(step===4&&form.tipo==='licenca_medica'&&!form.documento&&!form.documentoNome)return setError('Anexe o atestado médico para continuar.');setError('');setStep(value=>Math.min(5,value+1));}
  async function chooseFile(event){const file=event.target.files?.[0];if(!file)return setForm(current=>({...current,documento:null}));if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){event.target.value='';return setError('Envie PDF, JPG, PNG ou WebP com no máximo 5 MB.');}try{const dados=await readFile(file);setForm(current=>({...current,documento:{nome:file.name,dados}}));setError('');}catch(e){setError(e.message);}}
  function close(){setOpen(false);setEditingId(null);setStep(1);setForm(emptyForm);setError('');if(fileInput.current)fileInput.current.value='';}
  function create(category='ferias'){setEditingId(null);setStep(1);setForm({...emptyForm,categoria:category,tipo:category==='ferias'?'ferias':'licenca_medica'});setError('');setOpen(true);}
  function edit(item){setEditingId(item.id);setStep(2);setForm({usuarioId:String(item.usuarioId),categoria:item.tipo==='ferias'?'ferias':'afastamento',tipo:['licenca_medica','capacitacao'].includes(item.tipo)?item.tipo:'licenca_medica',dataInicio:iso(item.dataInicio),dataFim:iso(item.dataFim),retornoPrevisto:iso(item.retornoPrevisto),motivo:item.motivo||'',documento:null,documentoNome:item.documentoNome||''});setError('');setOpen(true);}
  async function save(){setSaving(true);setError('');try{const payload={...form,usuarioId:Number(form.usuarioId)};const result=editingId?await api.updatePersonnelLeave(editingId,payload,token):await api.createPersonnelLeave(payload,token);setMessage(result.alertaAtestadoLongo?`${result.message} Atenção: o atestado ultrapassa 30 dias corridos.`:result.message);close();await load();}catch(e){setError(e.message);}finally{setSaving(false);}}
  async function update(item,nextStatus){setSaving(true);setError('');try{await api.updatePersonnelLeaveStatus(item.id,nextStatus,token);setMessage(nextStatus==='concluido'?'Retorno confirmado e situação funcional atualizada.':'Registro cancelado com histórico preservado.');await load();}catch(e){setError(e.message);}finally{setSaving(false);}}
  const selected=employees.find(item=>String(item.id)===String(form.usuarioId));
  const cards=[['Em férias',data.resumo.emFerias,CalendarDays,'green'],['Afastados',data.resumo.afastados,UsersRound,'blue'],['Retornos próximos',data.resumo.retornosProximos,Clock3,'orange'],['Pendências',data.resumo.pendencias,FileBarChart,'red']];
  return <div className="administration-shell"><AdministracaoSidebar user={user} onLogout={onLogout}/><main className="administration-main leave-page">
    <header className="administration-topbar"><div><small>SECRETARIA ADMINISTRATIVA &gt; GESTÃO DE PESSOAS</small><h1>Férias e Afastamentos</h1><p>Conceda férias, registre afastamentos e ajuste períodos no calendário.</p></div><div className="leave-header-actions"><button className="leave-secondary-action" type="button" onClick={()=>create('afastamento')}>Registrar afastamento</button><button className="leave-primary" type="button" onClick={()=>create('ferias')}><Plus aria-hidden="true"/>Dar férias</button></div></header>
    <div className="leave-content">{error&&<div className="leave-feedback error" role="alert"><FileBarChart/>{error}<button onClick={load}>Tentar novamente</button></div>}{message&&<div className="leave-feedback success"><CheckCircle2/>{message}<button aria-label="Fechar mensagem" onClick={()=>setMessage('')}><X/></button></div>}
      <section className="leave-metrics">{cards.map(([label,value,Icon,tone])=><article className={tone} key={label}><span><Icon/></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</section>
      {data.alertasAtestadosLongos.length>0&&<section className="medical-alerts" role="alert"><header><AlertTriangle/><div><strong>Atestados acima de 30 dias corridos</strong><small>Revise os documentos e os encaminhamentos administrativos necessários.</small></div></header><div>{data.alertasAtestadosLongos.map(item=><span key={item.id}><b>{item.nome}</b><small>{item.diasCorridos} dias · {date(item.dataInicio)} a {date(item.dataFim)}</small><button type="button" onClick={()=>edit(item)}>Revisar período</button></span>)}</div></section>}
      {data.alertas.length>0&&<section className="return-alerts"><header><div><CheckCircle2/><span><strong>Retornos nos próximos 15 dias</strong><small>Acompanhe os servidores que retornarão em breve.</small></span></div></header><div>{data.alertas.map(item=><span key={item.id}><b>{item.nome}</b><small>{typeLabels[item.tipo]||item.tipo} · retorno em {date(item.retornoPrevisto)}</small></span>)}</div></section>}
      <section className="leave-panel"><header><div><h2>Registros funcionais</h2><p>Férias, atestados médicos e cursos de aperfeiçoamento.</p></div><div className="leave-filters"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar funcionário ou escola"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas as situações</option><option>Programado</option><option>Em andamento</option><option>Retorno pendente</option><option>Concluído</option><option>Cancelado</option></select></div></header>
        {loading?<div className="leave-skeleton">{[1,2,3,4].map(i=><span key={i}/>)}</div>:filtered.length===0?<div className="leave-empty"><Clock3/><h3>Nenhum registro encontrado</h3><p>Ajuste os filtros, conceda férias ou registre um afastamento.</p><button onClick={()=>create('ferias')}>Dar férias</button></div>:<div className="leave-table-scroll"><table><thead><tr><th>Funcionário</th><th>Modalidade</th><th>Período</th><th>Retorno previsto</th><th>Escola</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{filtered.map(item=><tr className={item.alertaAtestadoLongo?'long-medical-row':''} key={item.id}><td><strong>{item.nome}</strong><small>{item.matricula||'Sem matrícula'}</small></td><td><strong>{typeLabels[item.tipo]||item.tipo}</strong><small>{item.diasCorridos||days(iso(item.dataInicio),iso(item.dataFim))} dias corridos{item.alertaAtestadoLongo?' · requer atenção':''}</small></td><td>{date(item.dataInicio)} a {date(item.dataFim)}</td><td>{date(item.retornoPrevisto)}</td><td>{item.escola}</td><td><span className={`leave-status ${item.situacao.toLowerCase().replaceAll(' ','-')}`}>{item.situacao}</span></td><td><div className="leave-row-actions">{item.documentoNome&&<button title="Baixar documento" onClick={()=>api.downloadPersonnelLeaveDocument(item.id,item.documentoNome,token)}><FileBarChart/></button>}{item.status==='confirmado'&&<button title="Editar período" onClick={()=>edit(item)}><Pencil/> Editar</button>}{item.situacao==='Retorno pendente'&&<button className="complete" disabled={saving} onClick={()=>update(item,'concluido')}>Confirmar retorno</button>}{!['Concluído','Cancelado'].includes(item.situacao)&&<button className="cancel" disabled={saving} onClick={()=>update(item,'cancelado')}>Cancelar</button>}</div></td></tr>)}</tbody></table></div>}
      </section>
    </div>
    {open&&<aside className="leave-drawer" aria-label={editingId?'Editar férias ou afastamento':'Novo registro de férias ou afastamento'}><div className="leave-drawer-backdrop" onClick={close}/><section><header><div><small>ETAPA {step} DE 5</small><h2>{editingId?'Editar registro':form.categoria==='ferias'?'Dar férias':'Registrar afastamento'}</h2></div><button aria-label="Fechar" onClick={close}><X/></button></header><div className="leave-steps">{['Funcionário','Modalidade e período','Motivo','Documento','Confirmar'].map((label,index)=><span className={step>=index+1?'active':''} key={label}><b>{index+1}</b>{label}</span>)}</div><div className="leave-form-step">
      {step===1&&<label>Funcionário<select name="usuarioId" value={form.usuarioId} onChange={change}><option value="">Selecione</option>{employees.map(item=><option value={item.id} key={item.id}>{item.nome} · {item.matriculaFuncional||item.perfil}</option>)}</select></label>}
      {step===2&&<><label>Modalidade<select name="categoria" value={form.categoria} onChange={change} disabled={Boolean(editingId)}><option value="ferias">Férias</option><option value="afastamento">Afastamento</option></select></label>{form.categoria==='afastamento'&&<label className="leave-kind">Tipo de afastamento<select name="tipo" value={form.tipo} onChange={change}><option value="licenca_medica">Atestado médico</option><option value="capacitacao">Curso de aperfeiçoamento</option></select></label>}<div className="calendar-period"><div className="leave-date-grid"><label>Início<input type="date" name="dataInicio" value={form.dataInicio} onChange={change}/></label><label>Fim<input type="date" name="dataFim" value={form.dataFim} min={form.dataInicio} onChange={change}/></label></div><label>Retorno previsto<input type="date" name="retornoPrevisto" value={form.retornoPrevisto} min={nextDay(form.dataFim)} onChange={change}/></label>{periodDays>0&&<div className={`period-summary ${longMedical?'warning':''}`}><CalendarDays/><span><strong>{periodDays} dias corridos</strong><small>{date(form.dataInicio)} a {date(form.dataFim)} · retorno em {date(form.retornoPrevisto)}</small></span></div>}{longMedical&&<p className="medical-warning"><AlertTriangle/> Este atestado ultrapassa 30 dias corridos e emitirá um alerta administrativo.</p>}</div></>}
      {step===3&&<label>Motivo e observações<textarea name="motivo" rows="7" value={form.motivo} onChange={change} placeholder={form.tipo==='capacitacao'?'Informe o curso, instituição e finalidade.':'Informe o motivo, referência administrativa e observações necessárias.'}/></label>}
      {step===4&&<div className="leave-upload"><FileBarChart/><h3>{form.tipo==='licenca_medica'?'Atestado médico':'Documento comprobatório'}</h3><p>{form.tipo==='licenca_medica'?'Obrigatório':'Opcional'} · PDF, JPG, PNG ou WebP · até 5 MB.</p><label>Selecionar documento<input ref={fileInput} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={chooseFile}/></label>{(form.documento||form.documentoNome)&&<span>{form.documento?.nome||form.documentoNome} {form.documentoNome&&!form.documento?'(documento atual)':''}</span>}</div>}
      {step===5&&<div className="leave-review"><h3>Revise antes de confirmar</h3><dl><div><dt>Funcionário</dt><dd>{selected?.nome}</dd></div><div><dt>Modalidade</dt><dd>{typeLabels[form.tipo]}</dd></div><div><dt>Período</dt><dd>{date(form.dataInicio)} a {date(form.dataFim)} · {periodDays} dias corridos</dd></div><div><dt>Retorno</dt><dd>{date(form.retornoPrevisto)}</dd></div><div><dt>Documento</dt><dd>{form.documento?.nome||form.documentoNome||'Não anexado'}</dd></div><div><dt>Motivo</dt><dd>{form.motivo}</dd></div></dl>{longMedical&&<p className="medical-warning"><AlertTriangle/> Alerta de atestado superior a 30 dias será emitido.</p>}</div>}
    </div>{error&&<p className="drawer-error">{error}</p>}<footer>{step>1&&<button className="secondary" onClick={()=>setStep(value=>value-1)}>Voltar</button>}{step<5?<button onClick={next}>Continuar</button>:<button disabled={saving} onClick={save}>{saving?'Salvando...':editingId?'Salvar alterações':'Confirmar registro'}</button>}</footer></section></aside>}
  </main></div>;
}
