import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, FileBarChart, Search, X } from 'lucide-react';
import AdministracaoSidebar from './AdministracaoSidebar';
import { api } from './services/api';
import { AdministrationEmpty, AdministrationError, AdministrationSkeleton } from './AdministrationState';
import './administracao-demandas.css';

const columns=['Recebida','Em análise','Autorizada','Em execução','Concluída'];
const stage=(status)=>status==='Enviada à Secretaria'?'Recebida':['Em análise pela Secretaria','Pendente na Secretaria'].includes(status)?'Em análise':['Autorizada para execução','Pendente na Administração'].includes(status)?'Autorizada':status==='Em execução'?'Em execução':'Concluída';
const date=(value)=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'Não definido';
const dateTime=(value)=>value?new Date(value).toLocaleString('pt-BR'):'—';
const overdue=(item)=>Boolean(item.prazo&&stage(item.status)!=='Concluída'&&String(item.prazo).slice(0,10)<new Date().toISOString().slice(0,10));

export default function AdministracaoDemandas({token,user,onLogout}){
  const [demands,setDemands]=useState([]);const [selected,setSelected]=useState(null);const [view,setView]=useState('list');const [search,setSearch]=useState('');const [note,setNote]=useState('');const [sector,setSector]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function load(selectedId=selected?.id){setLoading(true);setError('');try{const items=await api.listMunicipalDemands(token);setDemands(items||[]);if(selectedId)setSelected((items||[]).find(item=>item.id===selectedId)||null);}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load(null);},[token]);
  const filtered=useMemo(()=>demands.filter(item=>!search||`${item.id} ${item.titulo} ${item.escola} ${item.categoria} ${item.responsavel||''}`.toLowerCase().includes(search.toLowerCase())),[demands,search]);
  const summary=useMemo(()=>({novas:demands.filter(item=>stage(item.status)==='Recebida').length,urgentes:demands.filter(item=>item.prioridade==='Alta'&&stage(item.status)!=='Concluída').length,andamento:demands.filter(item=>stage(item.status)==='Em execução').length,atrasadas:demands.filter(overdue).length}),[demands]);
  async function act(action){if(action==='encaminhar'&&!sector.trim())return setError('Informe o setor responsável antes de encaminhar.');setSaving(true);setError('');setMessage('');const defaults={assumir:'Demanda assumida pela Secretaria Administrativa.',encaminhar:`Demanda encaminhada ao setor ${sector}.`,solicitar_informacao:'Solicitamos informações complementares à unidade escolar.',autorizar:'Demanda autorizada administrativamente.',executar:'Atendimento iniciado pelo setor responsável.',concluir:'Atendimento concluído e demanda finalizada.'};try{await api.actOnMunicipalDemand(selected.id,{acao:action,mensagem:note.trim()||defaults[action],setorResponsavel:action==='encaminhar'?sector.trim():null},token);setMessage('Alteração registrada no histórico da demanda.');setNote('');await load(selected.id);}catch(e){setError(e.message);}finally{setSaving(false);}}
  async function download(item){try{await api.downloadDemandAttachment(selected.id,item.id,item.nome,token);}catch(e){setError(e.message);}}
  function card(item){return <button className={`admin-demand-card ${overdue(item)?'overdue':''}`} type="button" onClick={()=>{setSelected(item);setSector(item.setorResponsavel||'');setNote('');}} key={item.id}><span><b>#{item.id}</b><i className={`priority ${item.prioridade.toLowerCase()}`}>{item.prioridade}</i></span><strong>{item.titulo}</strong><small>{item.escola}</small><small>{item.categoria} · prazo {date(item.prazo)}</small>{item.responsavel&&<em>Responsável: {item.responsavel}</em>}</button>}
  const currentStage=selected?stage(selected.status):'';
  return <div className="administration-shell"><AdministracaoSidebar user={user} onLogout={onLogout}/><main className="administration-main admin-demands-page">
    <header className="administration-topbar"><div><small>SECRETARIA ADMINISTRATIVA &gt; OPERAÇÕES</small><h1>Demandas</h1><p>Recebimento, encaminhamento e atendimento das solicitações das escolas.</p></div><div className="demand-view-switch"><button className={view==='list'?'active':''} onClick={()=>setView('list')}>Lista</button><button className={view==='kanban'?'active':''} onClick={()=>setView('kanban')}>Kanban</button></div></header>
    <div className="admin-demands-content">{error&&<AdministrationError message={error} onRetry={()=>load(null)}/>} {message&&<p className="admin-demand-feedback success" role="status">{message}</p>}
      <section className="admin-demand-metrics"><article><FileBarChart/><span><strong>{summary.novas}</strong><small>Novas</small></span></article><article className="urgent"><AlertTriangle/><span><strong>{summary.urgentes}</strong><small>Urgentes</small></span></article><article className="progress"><Clock3/><span><strong>{summary.andamento}</strong><small>Em andamento</small></span></article><article className="late"><AlertTriangle/><span><strong>{summary.atrasadas}</strong><small>Atrasadas</small></span></article></section>
      <section className="admin-demand-workspace"><header><div><h2>Fluxo operacional</h2><p>Diretor → Secretaria Administrativa → Setor responsável → Atendimento → Conclusão</p></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar protocolo, escola ou categoria"/></label></header>
        {loading?<AdministrationSkeleton rows={5} label="Carregando demandas"/>:filtered.length===0?<AdministrationEmpty title="Nenhuma demanda encontrada" description={search?'Revise o termo pesquisado ou limpe o filtro.':'As demandas enviadas pelas escolas aparecerão aqui para triagem e atendimento.'}/>:view==='list'?<div className="admin-demand-list">{filtered.map(card)}</div>:<div className="admin-demand-kanban">{columns.map(column=><section key={column}><header><b>{column}</b><span>{filtered.filter(item=>stage(item.status)===column).length}</span></header><div>{filtered.filter(item=>stage(item.status)===column).map(card)}</div></section>)}</div>}
      </section>
    </div>
    {selected&&<aside className="admin-demand-drawer"><div className="admin-demand-backdrop" onClick={()=>setSelected(null)}/><section><header><div><small>PROTOCOLO #{selected.id}</small><h2>{selected.titulo}</h2></div><button aria-label="Fechar" onClick={()=>setSelected(null)}><X/></button></header><div className="admin-demand-detail">
      <div className="detail-badges"><span>{currentStage}</span><i className={`priority ${selected.prioridade.toLowerCase()}`}>{selected.prioridade}</i>{overdue(selected)&&<b>Atrasada</b>}</div><p>{selected.descricao}</p>
      <dl><div><dt>Escola</dt><dd>{selected.escola}</dd></div><div><dt>Solicitante</dt><dd>{selected.criadoPor}</dd></div><div><dt>Categoria</dt><dd>{selected.categoria}</dd></div><div><dt>Prazo</dt><dd>{date(selected.prazo)}</dd></div><div><dt>Responsável</dt><dd>{selected.responsavel||'Não atribuído'}</dd></div><div><dt>Setor responsável</dt><dd>{selected.setorResponsavel||'Não encaminhada'}</dd></div></dl>
      {selected.anexos?.length>0&&<section className="detail-section"><h3>Fotos e anexos</h3><div className="detail-attachments">{selected.anexos.map(item=><button key={item.id} onClick={()=>download(item)}>📎 {item.nome}</button>)}</div></section>}
      {currentStage!=='Concluída'&&<section className="detail-section action-section"><h3>Ações</h3><label>Despacho ou observação<textarea value={note} onChange={e=>setNote(e.target.value)} rows="3" placeholder="A mensagem será registrada no histórico."/></label><label>Setor responsável<input value={sector} onChange={e=>setSector(e.target.value)} placeholder="Ex.: Manutenção, Patrimônio, Transporte"/></label><div>{!selected.responsavel&&<button disabled={saving} onClick={()=>act('assumir')}>Assumir demanda</button>}<button disabled={saving} onClick={()=>act('encaminhar')}>Encaminhar</button><button className="secondary" disabled={saving} onClick={()=>act('solicitar_informacao')}>Solicitar informação</button>{['Recebida','Em análise'].includes(currentStage)&&<button className="authorize" disabled={saving} onClick={()=>act('autorizar')}>Autorizar administrativamente</button>}{currentStage==='Autorizada'&&<button className="execute" disabled={saving} onClick={()=>act('executar')}>Marcar em execução</button>}{currentStage==='Em execução'&&<button className="complete" disabled={saving} onClick={()=>act('concluir')}>Concluir</button>}</div></section>}
      <section className="detail-section"><h3>Histórico</h3><div className="detail-history">{selected.historico?.map(item=><article key={item.id}><CheckCircle2/><div><b>{item.usuario||'Sistema'}</b><p>{item.mensagem}</p><small>{item.statusAnterior||'Início'} → {item.statusNovo} · {dateTime(item.criadoEm)}</small></div></article>)}</div></section>
    </div></section></aside>}
  </main></div>;
}
