import React,{useEffect,useMemo,useRef,useState}from'react';
import{Download,FileArchive,FileClock,FilePlus2,History,Search,UploadCloud,X}from'lucide-react';
import AdministracaoSidebar from'./AdministracaoSidebar';
import{AdministrationEmpty,AdministrationError,AdministrationSkeleton}from'./AdministrationState';
import{api}from'./services/api';
import'./administracao-documentos-funcionais.css';

const categories={identidade:'Identidade',cpf:'CPF',contrato:'Contrato',portaria:'Portaria',termo_posse:'Termo de posse',certificados:'Certificados',comprovantes:'Comprovantes',afastamento:'Documentos de afastamento',outros:'Outros'};
const empty={usuarioId:'',titulo:'',categoria:'identidade',data:new Date().toISOString().slice(0,10),validade:'',observacao:'',arquivo:null};
const date=value=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const size=value=>value<1024?`${value} B`:value<1048576?`${(value/1024).toFixed(1)} KB`:`${(value/1048576).toFixed(1)} MB`;
function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file);});}

export default function AdministracaoDocumentosFuncionais({token,user,onLogout}){
 const[employees,setEmployees]=useState([]),[employeeId,setEmployeeId]=useState(''),[documents,setDocuments]=useState([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[drawer,setDrawer]=useState(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[history,setHistory]=useState(null);const fileRef=useRef(),loadSequence=useRef(0);
 async function references(){try{const rows=await api.getPersonnelDocumentReferences(token);setEmployees(rows||[]);if(rows?.length)setEmployeeId(String(rows[0].id));}catch(e){setError(e.message);setLoading(false);}}
 async function load(id=employeeId){const sequence=++loadSequence.current;if(!id){setDocuments([]);setLoading(false);return;}setLoading(true);setError('');try{const rows=await api.listPersonnelDocuments(id,token);if(sequence===loadSequence.current)setDocuments(rows||[]);}catch(e){if(sequence===loadSequence.current)setError(e.message);}finally{if(sequence===loadSequence.current)setLoading(false);}}
 useEffect(()=>{references();},[token]);useEffect(()=>{if(employeeId)load(employeeId);},[employeeId]);
 const selected=employees.find(item=>String(item.id)===String(employeeId));const filtered=useMemo(()=>documents.filter(item=>!search||`${item.titulo} ${categories[item.categoria]} ${item.arquivoNome}`.toLowerCase().includes(search.toLowerCase())),[documents,search]);
 const metrics={total:documents.length,vigentes:documents.filter(i=>i.situacao==='Vigente').length,vencendo:documents.filter(i=>i.situacao==='Vence em breve').length,vencidos:documents.filter(i=>i.situacao==='Vencido').length};
 function openNew(){setDrawer({type:'new'});setForm({...empty,usuarioId:employeeId});setError('');}
 function openVersion(item){setDrawer({type:'version',item});setForm({...empty,usuarioId:employeeId,titulo:item.titulo,categoria:item.categoria});setError('');}
 async function choose(event){const file=event.target.files?.[0];if(!file)return;if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){event.target.value='';return setError('Envie PDF, JPG, PNG ou WebP com no máximo 5 MB.');}try{setForm(current=>({...current,arquivo:{nome:file.name,dados:await readFile(file)}}));}catch(e){setError(e.message);}}
 async function save(event){event.preventDefault();if(!form.arquivo)return setError('Selecione o arquivo do documento.');setSaving(true);setError('');try{const result=drawer.type==='new'?await api.createPersonnelDocument({...form,usuarioId:Number(employeeId)},token):await api.createPersonnelDocumentVersion(drawer.item.id,form,token);setMessage(result.message);setDrawer(null);setHistory(null);await load();}catch(e){setError(e.message);}finally{setSaving(false);}}
 async function download(documentItem,version){try{await api.downloadPersonnelDocumentVersion(documentItem.id,version.id,version.arquivoNome,token);}catch(e){setError(e.message);}}
 return <div className="administration-shell"><AdministracaoSidebar user={user} onLogout={onLogout}/><main className="administration-main personnel-documents-page"><header className="administration-topbar"><div><small>SECRETARIA ADMINISTRATIVA &gt; GESTÃO DE PESSOAS</small><h1>Documentos Funcionais</h1><p>Prontuário digital administrativo com histórico permanente de versões.</p></div><button className="personnel-doc-primary" disabled={!employeeId} onClick={openNew}><FilePlus2/>Adicionar documento</button></header><div className="personnel-doc-content">
 {error&&<AdministrationError message={error} onRetry={()=>employeeId?load():references()}/>} {message&&<p className="personnel-doc-feedback success" role="status">{message}</p>}
 <section className="personnel-doc-employee"><div><span>FUNCIONÁRIO</span><h2>{selected?.nome||'Selecione um funcionário'}</h2><p>{selected?[selected.matricula,selected.cargo,selected.escola].filter(Boolean).join(' · '):'Escolha o servidor para consultar o prontuário.'}</p></div><select value={employeeId} onChange={e=>{setEmployeeId(e.target.value);setHistory(null);setMessage('');}}><option value="">Selecione</option>{employees.map(item=><option key={item.id} value={item.id}>{item.nome} · {item.matricula||'sem matrícula'}</option>)}</select></section>
 <section className="personnel-doc-metrics"><article><FileArchive/><span><strong>{metrics.total}</strong><small>Documentos</small></span></article><article className="green"><FileArchive/><span><strong>{metrics.vigentes}</strong><small>Vigentes</small></span></article><article className="orange"><FileClock/><span><strong>{metrics.vencendo}</strong><small>Vencem em 30 dias</small></span></article><article className="red"><FileClock/><span><strong>{metrics.vencidos}</strong><small>Vencidos</small></span></article></section>
 <section className="personnel-doc-panel"><header><div><h2>Documentos</h2><p>Nenhum arquivo anterior é substituído ou apagado.</p></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar documento ou categoria"/></label></header>{loading?<AdministrationSkeleton rows={5} label="Carregando prontuário"/>:filtered.length===0?<AdministrationEmpty title="Nenhum documento funcional encontrado" description="Adicione o primeiro documento ao prontuário deste funcionário." action={<button onClick={openNew}>Adicionar documento</button>}/>:<div className="personnel-doc-table"><table><thead><tr><th>Documento</th><th>Categoria</th><th>Data</th><th>Validade</th><th>Situação</th><th>Versão</th><th>Ações</th></tr></thead><tbody>{filtered.map(item=><React.Fragment key={item.id}><tr><td><b>{item.titulo}</b><small>{item.arquivoNome} · {size(item.arquivoTamanho)}</small></td><td>{categories[item.categoria]}</td><td>{date(item.data)}</td><td>{date(item.validade)}</td><td><span className={`personnel-doc-status ${item.situacao.toLowerCase().replaceAll(' ','-')}`}>{item.situacao}</span></td><td>v{item.versao}</td><td><div className="personnel-doc-actions"><button onClick={()=>download(item,item.versoes[0])}><Download/>Baixar</button><button onClick={()=>openVersion(item)}><UploadCloud/>Nova versão</button><button onClick={()=>setHistory(history===item.id?null:item.id)}><History/>Histórico</button></div></td></tr>{history===item.id&&<tr className="personnel-doc-history-row"><td colSpan="7"><div><h3>Histórico de versões</h3>{item.versoes.map(version=><article key={version.id}><span>v{version.versao}</span><div><b>{version.arquivoNome}</b><small>Documento de {date(version.data)} · incluído em {new Date(version.criadoEm).toLocaleString('pt-BR')} por {version.criadoPor||'Sistema'}</small>{version.observacao&&<p>{version.observacao}</p>}</div><button onClick={()=>download(item,version)}><Download/>Baixar</button></article>)}</div></td></tr>}</React.Fragment>)}</tbody></table></div>}</section>
 </div>{drawer&&<aside className="personnel-doc-drawer"><div className="personnel-doc-backdrop" onClick={()=>setDrawer(null)}/><form onSubmit={save}><header><div><small>{drawer.type==='new'?'NOVO DOCUMENTO':'NOVA VERSÃO'}</small><h2>{drawer.type==='new'?'Adicionar ao prontuário':drawer.item.titulo}</h2></div><button type="button" aria-label="Fechar formulário" onClick={()=>setDrawer(null)}><X/></button></header>{error&&<p className="personnel-doc-drawer-error" role="alert">{error}</p>}<div className="personnel-doc-form">{drawer.type==='new'&&<><label>Documento<input required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} placeholder="Ex.: Contrato de trabalho"/></label><label>Categoria<select value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}>{Object.entries(categories).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></>}<div className="personnel-doc-date-grid"><label>Data do documento<input required type="date" value={form.data} onChange={e=>setForm({...form,data:e.target.value})}/></label><label>Validade<input type="date" value={form.validade} onChange={e=>setForm({...form,validade:e.target.value})}/></label></div><label>Observação<textarea rows="3" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})} placeholder="Motivo da nova versão ou informação administrativa."/></label><div className="personnel-doc-upload"><UploadCloud/><h3>Enviar arquivo</h3><p>PDF, JPG, PNG ou WebP · máximo de 5 MB.</p><label>Selecionar arquivo<input ref={fileRef} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={choose}/></label>{form.arquivo&&<b>{form.arquivo.nome}</b>}</div>{drawer.type==='version'&&<p className="personnel-doc-version-notice"><History/>A versão atual será preservada integralmente no histórico.</p>}</div><footer><button type="button" className="secondary" onClick={()=>setDrawer(null)}>Cancelar</button><button disabled={saving}>{saving?'Enviando…':drawer.type==='new'?'Adicionar documento':'Adicionar nova versão'}</button></footer></form></aside>}</main></div>;
}
