import React, { useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, FileBarChart, Plus, Search, UsersRound, X } from 'lucide-react';
import AdministracaoSidebar from './AdministracaoSidebar';
import { api } from './services/api';
import './administracao-afastamentos.css';

const typeLabels={ferias:'Férias',licenca:'Licença',licenca_medica:'Licença médica',licenca_parental:'Licença maternidade/paternidade',afastamento_administrativo:'Afastamento administrativo',capacitacao:'Capacitação',outros:'Outros'};
const initialForm={usuarioId:'',tipo:'ferias',dataInicio:'',dataFim:'',retornoPrevisto:'',motivo:'',documento:null};
const readFile=(file)=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Não foi possível ler o documento.'));reader.readAsDataURL(file);});
const date=(value)=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';

export default function AdministracaoAfastamentos({token,user,onLogout}){
  const [data,setData]=useState({dados:[],resumo:{emFerias:0,afastados:0,retornosProximos:0,pendencias:0},alertas:[]});
  const [employees,setEmployees]=useState([]);const [form,setForm]=useState(initialForm);const [step,setStep]=useState(1);const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const fileInput=useRef(null);
  async function load(){setLoading(true);setError('');try{const [leaves,users]=await Promise.all([api.listPersonnelLeaves(token),api.listUsers(token)]);setData(leaves);setEmployees((Array.isArray(users)?users:users.dados||[]).filter(item=>Number(item.nivel)>3&&item.situacaoFuncional!=='desligado'));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[token]);
  const filtered=useMemo(()=>data.dados.filter(item=>(!search||`${item.nome} ${item.matricula||''} ${item.escola} ${typeLabels[item.tipo]}`.toLowerCase().includes(search.toLowerCase()))&&(!status||item.situacao===status)),[data.dados,search,status]);
  function change(event){setForm(current=>({...current,[event.target.name]:event.target.value}));setError('');}
  function next(){if(step===1&&!form.usuarioId)return setError('Selecione um funcionário.');if(step===2&&(!form.dataInicio||!form.dataFim||!form.retornoPrevisto))return setError('Informe o período e o retorno previsto.');if(step===3&&form.motivo.trim().length<5)return setError('Descreva o motivo do afastamento.');setError('');setStep(value=>Math.min(5,value+1));}
  async function chooseFile(event){const file=event.target.files?.[0];if(!file)return setForm(current=>({...current,documento:null}));if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){event.target.value='';return setError('Envie PDF, JPG, PNG ou WebP com no máximo 5 MB.');}try{const dados=await readFile(file);setForm(current=>({...current,documento:{nome:file.name,dados}}));}catch(e){setError(e.message);}}
  function close(){setOpen(false);setStep(1);setForm(initialForm);setError('');if(fileInput.current)fileInput.current.value='';}
  async function save(){setSaving(true);setError('');try{await api.createPersonnelLeave({...form,usuarioId:Number(form.usuarioId)},token);setMessage('Férias ou afastamento registrado com sucesso.');close();await load();}catch(e){setError(e.message);}finally{setSaving(false);}}
  async function update(item,nextStatus){setSaving(true);setError('');try{await api.updatePersonnelLeaveStatus(item.id,nextStatus,token);setMessage(nextStatus==='concluido'?'Retorno confirmado e situação funcional atualizada.':'Registro cancelado com histórico preservado.');await load();}catch(e){setError(e.message);}finally{setSaving(false);}}
  const selected=employees.find(item=>String(item.id)===String(form.usuarioId));
  const cards=[['Em férias',data.resumo.emFerias,CalendarDays,'green'],['Afastados',data.resumo.afastados,UsersRound,'blue'],['Retornos próximos',data.resumo.retornosProximos,Clock3,'orange'],['Pendências',data.resumo.pendencias,FileBarChart,'red']];
  return <div className="administration-shell"><AdministracaoSidebar user={user} onLogout={onLogout}/><main className="administration-main leave-page">
    <header className="administration-topbar"><div><small>SECRETARIA ADMINISTRATIVA &gt; GESTÃO DE PESSOAS</small><h1>Férias e Afastamentos</h1><p>Controle de períodos temporários, retornos e documentos funcionais.</p></div><button className="leave-primary" type="button" onClick={()=>setOpen(true)}><Plus aria-hidden="true"/>Novo registro</button></header>
    <div className="leave-content">{error&&<div className="leave-feedback error" role="alert"><FileBarChart/>{error}<button onClick={load}>Tentar novamente</button></div>}{message&&<div className="leave-feedback success"><CheckCircle2/>{message}<button aria-label="Fechar mensagem" onClick={()=>setMessage('')}><X/></button></div>}
      <section className="leave-metrics">{cards.map(([label,value,Icon,tone])=><article className={tone} key={label}><span><Icon/></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</section>
      {data.alertas.length>0&&<section className="return-alerts"><header><div><CheckCircle2/><span><strong>Retornos nos próximos 15 dias</strong><small>Acompanhe os servidores que retornarão em breve.</small></span></div></header><div>{data.alertas.map(item=><span key={item.id}><b>{item.nome}</b><small>{typeLabels[item.tipo]} · retorno em {date(item.retornoPrevisto)}</small></span>)}</div></section>}
      <section className="leave-panel"><header><div><h2>Registros funcionais</h2><p>Períodos confirmados e histórico de retornos.</p></div><div className="leave-filters"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar funcionário ou escola"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas as situações</option><option>Programado</option><option>Em andamento</option><option>Retorno pendente</option><option>Concluído</option><option>Cancelado</option></select></div></header>
        {loading?<div className="leave-skeleton">{[1,2,3,4].map(i=><span key={i}/>)}</div>:filtered.length===0?<div className="leave-empty"><Clock3/><h3>Nenhum afastamento encontrado</h3><p>Ajuste os filtros ou registre um novo período funcional.</p><button onClick={()=>setOpen(true)}>Novo registro</button></div>:<div className="leave-table-scroll"><table><thead><tr><th>Funcionário</th><th>Tipo</th><th>Início</th><th>Retorno previsto</th><th>Escola</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.nome}</strong><small>{item.matricula||'Sem matrícula'}</small></td><td>{typeLabels[item.tipo]}</td><td>{date(item.dataInicio)}</td><td>{date(item.retornoPrevisto)}</td><td>{item.escola}</td><td><span className={`leave-status ${item.situacao.toLowerCase().replaceAll(' ','-')}`}>{item.situacao}</span></td><td><div className="leave-row-actions">{item.documentoNome&&<button title="Baixar documento" onClick={()=>api.downloadPersonnelLeaveDocument(item.id,item.documentoNome,token)}><FileBarChart/></button>}{item.situacao==='Retorno pendente'&&<button className="complete" disabled={saving} onClick={()=>update(item,'concluido')}>Confirmar retorno</button>}{!['Concluído','Cancelado'].includes(item.situacao)&&<button className="cancel" disabled={saving} onClick={()=>update(item,'cancelado')}>Cancelar</button>}</div></td></tr>)}</tbody></table></div>}
      </section>
    </div>
    {open&&<aside className="leave-drawer" aria-label="Novo registro de férias ou afastamento"><div className="leave-drawer-backdrop" onClick={close}/><section><header><div><small>ETAPA {step} DE 5</small><h2>Novo registro</h2></div><button aria-label="Fechar" onClick={close}><X/></button></header><div className="leave-steps">{['Funcionário','Tipo e período','Motivo','Documento','Confirmar'].map((label,index)=><span className={step>=index+1?'active':''} key={label}><b>{index+1}</b>{label}</span>)}</div><div className="leave-form-step">
      {step===1&&<label>Funcionário<select name="usuarioId" value={form.usuarioId} onChange={change}><option value="">Selecione</option>{employees.map(item=><option value={item.id} key={item.id}>{item.nome} · {item.matriculaFuncional||item.perfil}</option>)}</select></label>}
      {step===2&&<><label>Tipo<select name="tipo" value={form.tipo} onChange={change}>{Object.entries(typeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="leave-date-grid"><label>Início<input type="date" name="dataInicio" value={form.dataInicio} onChange={change}/></label><label>Fim<input type="date" name="dataFim" value={form.dataFim} onChange={change}/></label></div><label>Retorno previsto<input type="date" name="retornoPrevisto" value={form.retornoPrevisto} onChange={change}/></label></>}
      {step===3&&<label>Motivo e observações<textarea name="motivo" rows="7" value={form.motivo} onChange={change} placeholder="Informe o motivo, referência administrativa e observações necessárias."/></label>}
      {step===4&&<div className="leave-upload"><FileBarChart/><h3>Documento comprobatório</h3><p>Opcional · PDF, JPG, PNG ou WebP · até 5 MB.</p><label>Selecionar documento<input ref={fileInput} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={chooseFile}/></label>{form.documento&&<span>{form.documento.nome}</span>}</div>}
      {step===5&&<div className="leave-review"><h3>Revise antes de confirmar</h3><dl><div><dt>Funcionário</dt><dd>{selected?.nome}</dd></div><div><dt>Tipo</dt><dd>{typeLabels[form.tipo]}</dd></div><div><dt>Período</dt><dd>{date(form.dataInicio)} a {date(form.dataFim)}</dd></div><div><dt>Retorno</dt><dd>{date(form.retornoPrevisto)}</dd></div><div><dt>Documento</dt><dd>{form.documento?.nome||'Não anexado'}</dd></div><div><dt>Motivo</dt><dd>{form.motivo}</dd></div></dl></div>}
    </div>{error&&<p className="drawer-error">{error}</p>}<footer>{step>1&&<button className="secondary" onClick={()=>setStep(value=>value-1)}>Voltar</button>}{step<5?<button onClick={next}>Continuar</button>:<button disabled={saving} onClick={save}>{saving?'Salvando...':'Confirmar registro'}</button>}</footer></section></aside>}
  </main></div>;
}
