import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,ClipboardList,Package,Plus,Send,Truck,X} from 'lucide-react';
import {Link} from 'react-router-dom';
import AdministracaoSidebar from './AdministracaoSidebar';
import {api} from './services/api';
import './almoxarifado.css';

const emptyProduct={item:'',categoria:'Material de expediente',unidade:'unidade',quantidade:'',estoqueMinimo:'',localizacao:''};
const emptyRequest={escolaId:'',justificativa:'',itens:[{produtoId:'',quantidade:''}]};
const nextAction={Solicitada:['analisar','Iniciar análise'],Autorizada:['separar','Iniciar separação'],'Em separação':['entregar','Registrar entrega']};

export default function Almoxarifado({token,user,onLogout}){
 const [data,setData]=useState({produtos:[],solicitacoes:[],escolas:[],resumo:{},podeAdministrar:false});const [product,setProduct]=useState(emptyProduct);const [request,setRequest]=useState(emptyRequest);const [modal,setModal]=useState('');const [selected,setSelected]=useState(null);const [authorized,setAuthorized]=useState({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function load(selectedId=selected?.id){setLoading(true);try{const result=await api.getInventory(token);setData(result);if(selectedId)setSelected(result.solicitacoes.find(item=>item.id===selectedId)||null);if(!request.escolaId&&result.escolas.length===1)setRequest(current=>({...current,escolaId:String(result.escolas[0].id)}));}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load(null);},[token]);
 const lowStock=useMemo(()=>data.produtos.filter(item=>item.estoqueBaixo),[data.produtos]);
 async function saveProduct(e){e.preventDefault();setSaving(true);setError('');try{const result=await api.createInventoryProduct({...product,quantidade:Number(product.quantidade||0),estoqueMinimo:Number(product.estoqueMinimo||0)},token);setMessage(result.message);setProduct(emptyProduct);setModal('');await load(null);}catch(err){setError(err.message);}finally{setSaving(false);}}
 async function saveRequest(e){e.preventDefault();setSaving(true);setError('');try{const payload={escolaId:Number(request.escolaId),justificativa:request.justificativa,itens:request.itens.filter(item=>item.produtoId&&item.quantidade).map(item=>({produtoId:Number(item.produtoId),quantidade:Number(item.quantidade)}))};const result=await api.createInventoryRequest(payload,token);setMessage(`${result.message} Protocolo ${result.protocolo}.`);setRequest({...emptyRequest,escolaId:data.escolas.length===1?String(data.escolas[0].id):''});setModal('');await load(null);}catch(err){setError(err.message);}finally{setSaving(false);}}
 function openDetail(item){setSelected(item);setAuthorized(Object.fromEntries(item.itens.map(line=>[line.produtoId,String(line.quantidadeAutorizada??line.quantidadeSolicitada)])));}
 async function act(acao){setSaving(true);setError('');try{const payload={acao,observacao:null};if(acao==='autorizar')payload.itens=selected.itens.map(item=>({produtoId:item.produtoId,quantidadeAutorizada:Number(authorized[item.produtoId]||0)}));const result=await api.actOnInventoryRequest(selected.id,payload,token);setMessage(result.message);await load(selected.id);}catch(e){setError(e.message);}finally{setSaving(false);}}
 const metrics=[['Itens cadastrados',data.resumo.itensCadastrados||0,Package],['Estoque baixo',data.resumo.estoqueBaixo||0,AlertTriangle],['Solicitações abertas',data.resumo.solicitacoesAbertas||0,ClipboardList],['Entregas pendentes',data.resumo.entregasPendentes||0,Truck]];
 const content=<main className="inventory-main"><header className="inventory-top"><div>{!data.podeAdministrar&&<Link to="/diretor">← Portal do Diretor</Link>}<small>{data.podeAdministrar?'SECRETARIA ADMINISTRATIVA > OPERAÇÕES':'UNIDADE ESCOLAR > SOLICITAÇÕES'}</small><h1>Almoxarifado</h1><p>Controle de materiais, solicitações e entregas da rede municipal.</p></div><div>{data.podeAdministrar&&<button className="secondary" onClick={()=>setModal('product')}><Plus/>Cadastrar produto</button>}<button onClick={()=>setModal('request')}><Send/>Nova solicitação</button></div></header><section className="inventory-body">{error&&<p className="inventory-feedback error">{error}</p>}{message&&<p className="inventory-feedback success">{message}</p>}<div className="inventory-metrics">{metrics.map(([label,value,Icon],index)=><article className={index===1&&value?'attention':''} key={label}><Icon/><span><strong>{value}</strong><small>{label}</small></span></article>)}</div>{data.podeAdministrar&&lowStock.length>0&&<section className="inventory-alert"><AlertTriangle/><div><b>Reposição necessária</b><p>{lowStock.map(item=>`${item.item} (${item.quantidade} ${item.unidade})`).join(' · ')}</p></div></section>}<section className="inventory-grid"><article className="inventory-panel"><header><h2>Produtos e saldos</h2><p>Estoque atualizado pelas movimentações confirmadas.</p></header><div className="inventory-table"><table><thead><tr><th>Item</th><th>Categoria</th><th>Unidade</th><th>Saldo</th><th>Mínimo</th><th>Localização</th></tr></thead><tbody>{data.produtos.map(item=><tr className={item.estoqueBaixo?'low':''} key={item.id}><td><b>{item.item}</b></td><td>{item.categoria}</td><td>{item.unidade}</td><td><strong>{item.quantidade}</strong></td><td>{item.estoqueMinimo}</td><td>{item.localizacao}</td></tr>)}</tbody></table>{!data.produtos.length&&!loading&&<p className="inventory-empty">Nenhum produto cadastrado.</p>}</div></article><article className="inventory-panel requests"><header><h2>Solicitações</h2><p>Acompanhe cada etapa até o recebimento.</p></header>{data.solicitacoes.map(item=><button className="request-card" onClick={()=>openDetail(item)} key={item.id}><span><b>{item.protocolo}</b><small>{item.escola}</small></span><span className={`inventory-status s-${item.status.toLowerCase().replaceAll(' ','-')}`}>{item.status}</span><small>{item.itens.length} item(ns) · {new Date(item.criadoEm).toLocaleDateString('pt-BR')}</small></button>)}{!data.solicitacoes.length&&!loading&&<p className="inventory-empty">Nenhuma solicitação registrada.</p>}</article></section></section></main>;
 return <div className={data.podeAdministrar?'administration-shell':'inventory-school-shell'}>{data.podeAdministrar&&<AdministracaoSidebar user={user} onLogout={onLogout}/>} {!data.podeAdministrar&&<button className="inventory-logout" onClick={onLogout}>Sair</button>}{content}
 {modal&&<div className="inventory-modal"><div className="inventory-backdrop" onClick={()=>setModal('')}/>{modal==='product'?<form onSubmit={saveProduct}><header><h2>Cadastrar produto</h2><button type="button" onClick={()=>setModal('')}><X/></button></header><label>Item<input required value={product.item} onChange={e=>setProduct({...product,item:e.target.value})}/></label><div className="inventory-form-grid"><label>Categoria<input required value={product.categoria} onChange={e=>setProduct({...product,categoria:e.target.value})}/></label><label>Unidade<input required value={product.unidade} onChange={e=>setProduct({...product,unidade:e.target.value})}/></label><label>Quantidade inicial<input type="number" min="0" step="0.01" required value={product.quantidade} onChange={e=>setProduct({...product,quantidade:e.target.value})}/></label><label>Estoque mínimo<input type="number" min="0" step="0.01" required value={product.estoqueMinimo} onChange={e=>setProduct({...product,estoqueMinimo:e.target.value})}/></label></div><label>Localização<input required value={product.localizacao} onChange={e=>setProduct({...product,localizacao:e.target.value})}/></label><footer><button disabled={saving}>{saving?'Salvando…':'Cadastrar produto'}</button></footer></form>:<form onSubmit={saveRequest}><header><h2>Solicitar materiais</h2><button type="button" onClick={()=>setModal('')}><X/></button></header><label>Escola<select required value={request.escolaId} onChange={e=>setRequest({...request,escolaId:e.target.value})}><option value="">Selecione</option>{data.escolas.map(item=><option value={item.id} key={item.id}>{item.nome}</option>)}</select></label>{request.itens.map((line,index)=><div className="request-line" key={index}><select required value={line.produtoId} onChange={e=>setRequest({...request,itens:request.itens.map((item,i)=>i===index?{...item,produtoId:e.target.value}:item)})}><option value="">Produto</option>{data.produtos.map(item=><option value={item.id} key={item.id}>{item.item} · saldo {item.quantidade}</option>)}</select><input aria-label="Quantidade" type="number" min="0.01" step="0.01" required value={line.quantidade} onChange={e=>setRequest({...request,itens:request.itens.map((item,i)=>i===index?{...item,quantidade:e.target.value}:item)})}/></div>)}<button type="button" className="add-line" onClick={()=>setRequest({...request,itens:[...request.itens,{produtoId:'',quantidade:''}]})}><Plus/>Adicionar item</button><label>Justificativa<textarea rows="4" required value={request.justificativa} onChange={e=>setRequest({...request,justificativa:e.target.value})}/></label><footer><button disabled={saving}>{saving?'Enviando…':'Enviar solicitação'}</button></footer></form>}</div>}
 {selected&&<aside className="inventory-drawer"><div className="inventory-backdrop" onClick={()=>setSelected(null)}/><section><header><div><small>{selected.protocolo}</small><h2>{selected.escola}</h2><p>{selected.status}</p></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="inventory-detail"><p><b>Solicitante:</b> {selected.solicitante}</p><p><b>Justificativa:</b> {selected.justificativa}</p><h3>Itens</h3>{selected.itens.map(item=><div className="authorized-line" key={item.produtoId}><span><b>{item.item}</b><small>Solicitado: {item.quantidadeSolicitada} {item.unidade}</small></span>{data.podeAdministrar&&selected.status==='Em análise'?<input type="number" min="0" step="0.01" value={authorized[item.produtoId]||''} onChange={e=>setAuthorized({...authorized,[item.produtoId]:e.target.value})}/>:<b>{item.quantidadeAutorizada??'—'}</b>}</div>)}{data.podeAdministrar&&selected.status==='Em análise'&&<button disabled={saving} onClick={()=>act('autorizar')}><CheckCircle2/>Autorizar quantidades</button>}{data.podeAdministrar&&nextAction[selected.status]&&<button disabled={saving} onClick={()=>act(nextAction[selected.status][0])}>{nextAction[selected.status][1]}</button>}{!data.podeAdministrar&&selected.status==='Entregue'&&<button disabled={saving} onClick={()=>act('confirmar')}><CheckCircle2/>Confirmar recebimento</button>}</div></section></aside>}
 </div>;
}
