import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './services/api';
import './coordenador-gestao-pedagogica.css';

const year = new Date().getFullYear();
const empty = {
  ac: { unidadeLetiva: 1, semanaInicio: '', areaConhecimento: 'Linguagens', pauta: '', encaminhamentos: '', participantes: '' },
  intervention: { unidadeLetiva: 1, turmaId: '', diagnostico: '', objetivos: '', acoes: '', responsaveis: '', prazo: '', indicadores: '', status: 'Em elaboração' },
  council: { unidadeLetiva: 1, turmaId: '', etapa: 'Parcial', dataReuniao: '', diagnosticoTurma: '', estudantesDestaque: '', estudantesAtencao: '', decisoes: '', participantes: '' },
  pei: { alunoId: '', necessidadesEducacionais: '', potencialidades: '', barreiras: '', objetivos: '', estrategiasAdaptacoes: '', recursosAcessibilidade: '', avaliacaoAcompanhamento: '', profissionaisEnvolvidos: '' },
};
const labels = { ac: 'AC semanal', intervention: 'Plano de intervenção', council: 'Conselho de classe', pei: 'PEI e inclusão' };

function Field({ label, children, wide = false }) { return <label className={wide ? 'ped-wide' : ''}><span>{label}</span>{children}</label>; }
function Text({ name, form, setForm, label, rows = 3, required = true }) { return <Field label={label} wide><textarea name={name} rows={rows} required={required} value={form[name]} onChange={(e)=>setForm({...form,[name]:e.target.value})}/></Field>; }

export default function CoordenadorGestaoPedagogica({ user, token, onLogout }) {
  const [tab,setTab]=useState('ac'); const [context,setContext]=useState({escolas:[],turmas:[],alunos:[]});
  const [escolaId,setEscolaId]=useState(''); const [anoLetivo,setAnoLetivo]=useState(year); const [records,setRecords]=useState({atividadesComplementares:[],intervencoes:[],conselhos:[],peis:[]});
  const [forms,setForms]=useState(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(''); const [error,setError]=useState('');
  const form=forms[tab]; const setForm=(value)=>setForms({...forms,[tab]:value});
  const turmas=useMemo(()=>context.turmas.filter(x=>String(x.escolaId)===String(escolaId)),[context,escolaId]);
  const alunos=useMemo(()=>context.alunos.filter(x=>String(x.escolaId)===String(escolaId)),[context,escolaId]);

  async function loadContext(){setLoading(true);try{const data=await api.getPedagogicalContext(token);setContext(data);const first=escolaId||data.escolas?.[0]?.id||'';setEscolaId(String(first));if(first)await loadRecords(first,anoLetivo);}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function loadRecords(school=escolaId,yearValue=anoLetivo){if(!school)return;try{setRecords(await api.getPedagogicalRecords({escolaId:school,anoLetivo:yearValue},token));}catch(e){setError(e.message);}}
  useEffect(()=>{loadContext();},[token]);
  useEffect(()=>{if(escolaId)loadRecords(escolaId,anoLetivo);},[escolaId,anoLetivo]);

  async function save(event){event.preventDefault();setSaving(true);setError('');setNotice('');try{const data={...form,escolaId:Number(escolaId),anoLetivo:Number(anoLetivo)};if(data.turmaId)data.turmaId=Number(data.turmaId);else delete data.turmaId;if(data.alunoId)data.alunoId=Number(data.alunoId);if(!data.prazo)delete data.prazo;await ({ac:api.createComplementaryActivity,intervention:api.createInterventionPlan,council:api.createClassCouncil,pei:api.createPei}[tab])(data,token);setForms({...forms,[tab]:empty[tab]});setNotice(`${labels[tab]} salvo com sucesso.`);await loadRecords();}catch(e){setError(e.message);}finally{setSaving(false);}}
  function printRecord(title,record){const school=context.escolas.find(x=>String(x.id)===String(escolaId))?.nome||'';const rows=Object.entries(record).filter(([key,value])=>value!=null&&value!==''&&!['id','escola_id','responsavel_id','criado_em','atualizado_em'].includes(key)).map(([key,value])=>`<tr><th>${key.replaceAll('_',' ')}</th><td>${String(value).replaceAll('<','&lt;').replaceAll('\n','<br>')}</td></tr>`).join('');const popup=window.open('','_blank');popup.document.write(`<html><head><title>${title}</title><style>body{font:14px Arial;margin:36px;color:#17233b}h1{color:#0b4b91}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccd5e2;padding:9px;text-align:left}th{width:25%;background:#eef4fb}.sign{margin-top:70px;display:flex;gap:50px}.sign div{flex:1;border-top:1px solid;text-align:center;padding-top:8px}</style></head><body><small>SIEDU · Secretaria Municipal de Educação</small><h1>${title}</h1><h3>${school} · ${anoLetivo}</h3><table>${rows}</table><div class="sign"><div>Coordenação pedagógica</div><div>Professores participantes</div></div><script>window.print()</script></body></html>`);popup.document.close();}

  return <div className="ped-page"><header className="ped-top"><div><Link to="/coordenacao">← Portal do Coordenador</Link><small>GESTÃO PEDAGÓGICA DA UNIDADE</small><h1>Planejamento, acompanhamento e inclusão</h1></div><div><b>{user?.nome}</b><button onClick={onLogout}>Sair</button></div></header><main>
    <section className="ped-filters"><Field label="Escola"><select value={escolaId} onChange={e=>setEscolaId(e.target.value)}>{context.escolas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Field><Field label="Ano letivo"><input type="number" value={anoLetivo} onChange={e=>setAnoLetivo(e.target.value)}/></Field></section>
    <nav className="ped-tabs" aria-label="Rotinas pedagógicas">{Object.entries(labels).map(([key,label])=><button className={tab===key?'active':''} onClick={()=>{setTab(key);setNotice('');setError('');}} key={key}>{label}</button>)}</nav>
    {error&&<p className="ped-error" role="alert">{error}</p>}{notice&&<p className="ped-success" role="status">{notice}</p>}
    {loading?<p>Carregando…</p>:<section className="ped-workspace"><form onSubmit={save} className="ped-card ped-form"><h2>Novo registro · {labels[tab]}</h2>
      {tab==='ac'&&<><Field label="Unidade letiva"><select value={form.unidadeLetiva} onChange={e=>setForm({...form,unidadeLetiva:Number(e.target.value)})}>{[1,2,3,4].map(x=><option key={x} value={x}>{x}ª unidade</option>)}</select></Field><Field label="Semana de referência"><input required type="date" value={form.semanaInicio} onChange={e=>setForm({...form,semanaInicio:e.target.value})}/></Field><Field label="Área do conhecimento"><select value={form.areaConhecimento} onChange={e=>setForm({...form,areaConhecimento:e.target.value})}>{['Linguagens','Matemática','Ciências da Natureza','Ciências Humanas','Educação Infantil/Anos Iniciais'].map(x=><option key={x}>{x}</option>)}</select></Field><Text name="pauta" form={form} setForm={setForm} label="Pauta e objetivos da AC"/><Text name="encaminhamentos" form={form} setForm={setForm} label="Discussões, decisões e encaminhamentos"/><Text name="participantes" form={form} setForm={setForm} label="Professores participantes" required={false}/></>}
      {tab==='intervention'&&<><Field label="Unidade letiva"><select value={form.unidadeLetiva} onChange={e=>setForm({...form,unidadeLetiva:Number(e.target.value)})}>{[1,2,3,4].map(x=><option key={x} value={x}>{x}ª unidade</option>)}</select></Field><Field label="Turma (opcional)"><select value={form.turmaId} onChange={e=>setForm({...form,turmaId:e.target.value})}><option value="">Toda a unidade</option>{turmas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Field><Text name="diagnostico" form={form} setForm={setForm} label="Diagnóstico da unidade anterior"/><Text name="objetivos" form={form} setForm={setForm} label="Objetivos de melhoria"/><Text name="acoes" form={form} setForm={setForm} label="Ações propostas"/><Text name="responsaveis" form={form} setForm={setForm} label="Responsáveis"/><Text name="indicadores" form={form} setForm={setForm} label="Indicadores e evidências de acompanhamento"/><Field label="Prazo"><input type="date" value={form.prazo} onChange={e=>setForm({...form,prazo:e.target.value})}/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['Em elaboração','Em execução','Concluído','Revisão necessária'].map(x=><option key={x}>{x}</option>)}</select></Field></>}
      {tab==='council'&&<><Field label="Unidade letiva"><select value={form.unidadeLetiva} onChange={e=>setForm({...form,unidadeLetiva:Number(e.target.value)})}>{[1,2,3,4].map(x=><option key={x} value={x}>{x}ª unidade</option>)}</select></Field><Field label="Turma"><select required value={form.turmaId} onChange={e=>setForm({...form,turmaId:e.target.value})}><option value="">Selecione</option>{turmas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Field><Field label="Etapa"><select value={form.etapa} onChange={e=>setForm({...form,etapa:e.target.value})}><option>Parcial</option><option>Final</option></select></Field><Field label="Data"><input required type="date" value={form.dataReuniao} onChange={e=>setForm({...form,dataReuniao:e.target.value})}/></Field><Text name="diagnosticoTurma" form={form} setForm={setForm} label="Diagnóstico geral da turma"/><Text name="estudantesDestaque" form={form} setForm={setForm} label="Avanços e estudantes em destaque" required={false}/><Text name="estudantesAtencao" form={form} setForm={setForm} label="Estudantes que precisam de intervenção" required={false}/><Text name="decisoes" form={form} setForm={setForm} label="Decisões e encaminhamentos"/><Text name="participantes" form={form} setForm={setForm} label="Participantes" required={false}/></>}
      {tab==='pei'&&<><p className="ped-privacy ped-wide">🔒 Dados pedagógicos sensíveis. Registre somente informações necessárias ao atendimento educacional e evite expor diagnóstico médico.</p><Field label="Estudante"><select required value={form.alunoId} onChange={e=>setForm({...form,alunoId:e.target.value})}><option value="">Selecione</option>{alunos.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Field><Text name="necessidadesEducacionais" form={form} setForm={setForm} label="Necessidades educacionais específicas"/><Text name="potencialidades" form={form} setForm={setForm} label="Potencialidades e interesses"/><Text name="barreiras" form={form} setForm={setForm} label="Barreiras identificadas"/><Text name="objetivos" form={form} setForm={setForm} label="Objetivos individualizados"/><Text name="estrategiasAdaptacoes" form={form} setForm={setForm} label="Estratégias e adaptações curriculares"/><Text name="recursosAcessibilidade" form={form} setForm={setForm} label="Recursos de acessibilidade" required={false}/><Text name="avaliacaoAcompanhamento" form={form} setForm={setForm} label="Critérios de avaliação e acompanhamento"/><Text name="profissionaisEnvolvidos" form={form} setForm={setForm} label="Profissionais e família envolvidos" required={false}/></>}
      <button className="ped-primary" disabled={saving||!escolaId}>{saving?'Salvando…':'Salvar registro'}</button></form>
      <section className="ped-card"><h2>Registros de {anoLetivo}</h2>{tab==='ac'&&(records.atividadesComplementares||[]).map(x=><article className="ped-record" key={x.id}><b>{x.area_conhecimento} · semana de {new Date(`${x.semana_inicio}T12:00`).toLocaleDateString('pt-BR')}</b><p>{x.pauta}</p><button onClick={()=>printRecord('Ata de Atividade Complementar (AC)',x)}>Gerar ata</button></article>)}{tab==='intervention'&&(records.intervencoes||[]).map(x=><article className="ped-record" key={x.id}><b>{x.unidade_letiva}ª unidade · {x.turma||'Toda a escola'}</b><p>{x.objetivos}</p><span>{x.status}</span></article>)}{tab==='council'&&(records.conselhos||[]).map(x=><article className="ped-record" key={x.id}><b>{x.etapa} · {x.turma} · {x.unidade_letiva}ª unidade</b><p>{x.decisoes}</p><button onClick={()=>printRecord(`Ata do Conselho de Classe ${x.etapa}`,x)}>Gerar ata</button></article>)}{tab==='pei'&&(records.peis||[]).map(x=><article className="ped-record" key={x.id}><b>{x.aluno}</b><p>Objetivos: {x.objetivos}</p><span>Atualizado em {new Date(x.atualizado_em).toLocaleDateString('pt-BR')}</span></article>)}{!(tab==='ac'?records.atividadesComplementares:tab==='intervention'?records.intervencoes:tab==='council'?records.conselhos:records.peis)?.length&&<p>Nenhum registro lançado neste ano.</p>}</section>
    </section>}
  </main></div>;
}
