import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './services/api';

const card = { background: '#fff', padding: 20, borderRadius: 14, boxShadow: '0 3px 15px #dce5f080' };
export default function CoordenadorPlanos({ token }) {
  const [plans, setPlans] = useState([]);
  const [selected, setSelected] = useState(null);
  const [parecer, setParecer] = useState('');
  const [notice, setNotice] = useState('');
  async function load() { try { setPlans(await api.listLessonPlansForReview('', token)); } catch (error) { setNotice(error.message); } }
  useEffect(() => { load(); }, [token]);
  async function review(acao) { if (!selected) return; if (acao === 'devolver' && !parecer.trim()) { setNotice('Escreva a orientação de correção.'); return; } try { const result = await api.reviewProfessorLessonPlan(selected.id, acao, parecer, token); setNotice(result.message); setSelected(null); setParecer(''); await load(); } catch (error) { setNotice(error.message); } }
  const pending = plans.filter((item) => item.status === 'Enviado para aprovação');
  return <div style={{ minHeight: '100vh', background: '#f4f7fc', color: '#09245a', fontFamily: 'Arial' }}><header style={{ background: '#fff', padding: '14px 4%', display: 'flex' }}><b style={{ fontSize: 23 }}>📋 Revisão de planos de aula</b><Link to="/coordenacao" style={{ marginLeft: 'auto' }}>← Portal da Coordenação</Link></header><main style={{ maxWidth: 1200, margin: 'auto', padding: '28px 4%' }}><h1>Envio, devolução e aprovação</h1><p>Há <b>{pending.length}</b> plano(s) aguardando análise no seu escopo de escolas.</p>{notice && <p style={{ background: '#eef5ff', padding: 12 }}>{notice}</p>}<section style={{ display: 'grid', gridTemplateColumns: selected ? '.9fr 1.1fr' : '1fr', gap: 18 }}><div>{plans.map((item) => <button key={item.id} onClick={() => { setSelected(item); setParecer(item.parecer || ''); }} style={{ ...card, width: '100%', border: selected?.id === item.id ? '2px solid #176fe3' : '2px solid transparent', textAlign: 'left', marginBottom: 12, color: '#09245a' }}><b>{item.tema}</b><p>{item.professor} · {item.turma} · {item.disciplina}</p><small>{item.escola} · {new Date(item.data).toLocaleDateString('pt-BR')} · versão {item.versao}</small><strong style={{ display: 'block', marginTop: 7 }}>{item.status}</strong></button>)}</div>{selected && <article style={card}><h2>{selected.tema}</h2><p><b>Professor:</b> {selected.professor}<br /><b>Turma:</b> {selected.turma} · <b>Data:</b> {new Date(selected.data).toLocaleDateString('pt-BR')}</p>{[['Objetivos', selected.objetivos], ['Habilidades BNCC', selected.habilidadesBncc], ['Conteúdos', selected.conteudos], ['Metodologia', selected.metodologia], ['Recursos', selected.recursos], ['Avaliação', selected.avaliacao], ['Adaptações inclusivas', selected.adaptacoesInclusivas], ['Tarefa para casa', selected.tarefaCasa]].map(([label, value]) => value && <div key={label}><h3>{label}</h3><p style={{ whiteSpace: 'pre-wrap' }}>{value}</p></div>)}{selected.status === 'Enviado para aprovação' && <><label><b>Parecer/orientação</b><textarea rows="5" value={parecer} onChange={(event) => setParecer(event.target.value)} style={{ width: '100%', boxSizing: 'border-box', marginTop: 7 }} /></label><div style={{ display: 'flex', gap: 10, marginTop: 12 }}><button onClick={() => review('aprovar')} style={{ background: '#16864b', color: '#fff', border: 0, padding: 11 }}>✅ Aprovar</button><button onClick={() => review('devolver')} style={{ background: '#c53b3b', color: '#fff', border: 0, padding: 11 }}>↩ Solicitar correção</button></div></>}</article>}</section></main></div>;
}
