import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const areas = [
  ['📘', 'Acompanhamento pedagógico', 'Supervisionar planos de aula, observar aulas e orientar didáticas.', '/coordenacao/planos'],
  ['🎓', 'Formação continuada', 'Planejar e registrar capacitações, HTPC e encontros formativos.', '/gestao-municipal?tab=agenda'],
  ['🤝', 'Mediação pedagógica', 'Mediar relações entre professores, direção e famílias.', '/coordenacao'],
  ['⚠️', 'Ocorrências e acompanhamento', 'Registrar ocorrências e acompanhar encaminhamentos disciplinares.', '/coordenacao'],
  ['📊', 'Avaliação institucional', 'Aplicar e analisar avaliações diagnósticas e resultados da rede.', '/gestao-municipal?tab=indicadores'],
];

export default function CoordenadorProfessores({ user, onLogout }) {
  const [active, setActive] = useState('acompanhamento');
  const [notice, setNotice] = useState('');
  const [records, setRecords] = useState([]);
  const [form, setForm] = useState({ professor: '', data: '', tema: '', descricao: '', status: 'Pendente' });
  const save = (event) => { event.preventDefault(); if (!form.professor || !form.descricao) return; setRecords((items) => [{ ...form, id: Date.now() }, ...items]); setNotice('Registro salvo no acompanhamento pedagógico.'); setForm({ professor: '', data: '', tema: '', descricao: '', status: 'Pendente' }); };
  const tabs = [['acompanhamento', '👀 Acompanhamento'], ['formacao', '🎓 Formação/HTPC'], ['mediacao', '🤝 Mediação'], ['ocorrencias', '⚠️ Ocorrências'], ['intervencao', '🧭 Intervenção']];
  return <div style={{ minHeight: '100vh', background: '#f4f7fc', color: '#09245a', fontFamily: 'Arial, sans-serif' }}>
    <header style={{ display: 'flex', alignItems: 'center', gap: 18, padding: '16px 4%', background: '#fff', borderBottom: '1px solid #dce5f0' }}><Link to="/coordenacao">← Portal do Coordenador</Link><b style={{ fontSize: 23 }}>👩‍🏫 Módulo de Professores</b><span style={{ marginLeft: 'auto' }}>{user?.nome}</span><button type="button" onClick={onLogout}>Sair</button></header>
    <main style={{ maxWidth: 1280, margin: 'auto', padding: '30px 4%' }}><small style={{ color: '#1476ef', fontWeight: 900, letterSpacing: '.12em' }}>COORDENAÇÃO PEDAGÓGICA</small><h1 style={{ margin: '7px 0' }}>Professores e aprendizagem</h1><p style={{ color: '#607399' }}>Integre planejamento, acompanhamento, formação e intervenção pedagógica em um único fluxo.</p>
      {notice && <p style={{ padding: 12, borderRadius: 8, background: '#e8f7ef', color: '#17633f' }}>{notice}</p>}
      <nav style={{ display: 'flex', flexWrap: 'wrap', gap: 8, margin: '22px 0 14px' }}>{tabs.map(([key, label]) => <button type="button" key={key} onClick={() => setActive(key)} style={{ padding: '10px 14px', border: 0, borderRadius: 9, background: active === key ? '#176fe3' : '#fff', color: active === key ? '#fff' : '#173d70', fontWeight: 800, cursor: 'pointer' }}>{label}</button>)}</nav>
      {active === 'acompanhamento' && <><section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 14 }}>{areas.map(([icon, title, text, link]) => <Link key={title} to={link} style={{ padding: 18, borderRadius: 13, background: '#fff', border: '1px solid #dce7f5', textDecoration: 'none', color: '#09245a' }}><span style={{ fontSize: 25 }}>{icon}</span><h2 style={{ fontSize: 16, margin: '8px 0 5px' }}>{title}</h2><p style={{ margin: 0, color: '#607399', fontSize: 12 }}>{text}</p></Link>)}</section><form onSubmit={save} style={{ marginTop: 18, padding: 20, borderRadius: 13, background: '#fff', border: '1px solid #dce7f5' }}><h2 style={{ marginTop: 0 }}>Registrar observação ou orientação</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 10 }}><input placeholder="Professor" value={form.professor} onChange={(e) => setForm({ ...form, professor: e.target.value })} /><input type="date" value={form.data} onChange={(e) => setForm({ ...form, data: e.target.value })} /><input placeholder="Tema (ex.: metodologia)" value={form.tema} onChange={(e) => setForm({ ...form, tema: e.target.value })} /><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>Pendente</option><option>Em acompanhamento</option><option>Concluído</option></select></div><textarea required placeholder="Descreva a orientação, devolutiva ou encaminhamento" value={form.descricao} onChange={(e) => setForm({ ...form, descricao: e.target.value })} style={{ width: '100%', boxSizing: 'border-box', minHeight: 80, marginTop: 10, padding: 10 }} /><button style={{ marginTop: 10, padding: '10px 16px', border: 0, borderRadius: 8, background: '#176fe3', color: '#fff', fontWeight: 800 }}>Salvar registro</button></form></>}
      {active !== 'acompanhamento' && <section style={{ padding: 24, borderRadius: 13, background: '#fff', border: '1px solid #dce7f5' }}><h2>{tabs.find(([key]) => key === active)?.[1]}</h2><p style={{ color: '#607399' }}>Registre e acompanhe ações conjuntas com os professores nesta área de trabalho.</p><form onSubmit={save}><input required placeholder="Professor ou grupo" value={form.professor} onChange={(e) => setForm({ ...form, professor: e.target.value })} style={{ padding: 11, marginRight: 8 }} /><textarea required placeholder="Descrição da ação, pauta ou encaminhamento" value={form.descricao} onChange={(e) => setForm({ ...form, descricao: e.target.value })} style={{ display: 'block', width: '100%', marginTop: 12, minHeight: 100, padding: 10 }} /><button style={{ marginTop: 10, padding: '10px 16px', border: 0, borderRadius: 8, background: '#176fe3', color: '#fff', fontWeight: 800 }}>Registrar ação</button></form></section>}
      {records.length > 0 && <section style={{ marginTop: 18, padding: 20, borderRadius: 13, background: '#fff', border: '1px solid #dce7f5' }}><h2>Registros recentes</h2>{records.map((record) => <article key={record.id} style={{ padding: 12, borderTop: '1px solid #edf1f7' }}><b>{record.professor}</b> · {record.tema || 'Ação pedagógica'} <span style={{ float: 'right', color: '#176fe3' }}>{record.status}</span><p style={{ margin: '5px 0', color: '#607399' }}>{record.descricao}</p></article>)}</section>}
    </main>
  </div>;
}
