import React,{useEffect,useMemo,useState}from'react';import{Link}from'react-router-dom';
import{AlertTriangle,BarChart3,Bell,Bus,CheckCircle2,CircleDollarSign,ClipboardCheck,FileBarChart,FileCheck2,LogOut,Menu,ReceiptText,Search,ShieldCheck,WalletCards,X}from'lucide-react';
import{api}from'./services/api';
import{prefeituraLogo}from'./prefeitura-logo';
import'./financeiro-fiscal.css';

const money=(value)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const short=(value)=>Number(value||0).toLocaleString('pt-BR',{notation:'compact',maximumFractionDigits:1});

function Sidebar({user,onLogout,open,setOpen}){
 const items=[['Painel Financeiro e Fiscal',BarChart3,'#visao'],['Orçamento e Execução',CircleDollarSign,'#execucao'],['Despesas e Pagamentos',WalletCards,'#execucao'],['Prestação de Contas',ClipboardCheck,'#prestacoes'],['Relatórios Fiscais',FileBarChart,'#prestacoes'],['Transportes',Bus,'#atalhos'],['Auditorias e Inspeções',ShieldCheck,'#auditorias']];
 return <><button className="finance-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>} Menu</button>{open&&<button className="finance-backdrop" onClick={()=>setOpen(false)} aria-label="Fechar menu"/>}<aside className={`finance-sidebar ${open?'open':''}`}><div className="finance-contractor"><img className="finance-city-logo" src={prefeituraLogo} alt="Prefeitura Municipal de Pindobaçu"/><span><strong>Prefeitura Municipal de Pindobaçu</strong><small>Contratante institucional</small></span></div><Link className="sidebar-system-home" to="/financeiro" aria-label="Voltar ao painel financeiro"><img src="/images/siedu-logo-transparent.svg" alt="SIEDU — Sistema Integrado de Educação"/></Link><nav><small>VISÃO GERAL</small>{items.map(([label,Icon,href],index)=><a className={index===0?'active':''} href={href} key={label} onClick={()=>setOpen(false)}><Icon/><span>{label}</span></a>)}</nav><footer><div><b>{user?.nome}</b><small>{user?.perfil}</small></div><button onClick={onLogout}><LogOut/>Sair</button></footer></aside></>;
}

function Metric({label,value,detail,Icon,tone}){return <article className={`finance-metric ${tone}`}><span><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>}

export default function FinanceiroFiscalDashboard({token,user,onLogout}){
 const[data,setData]=useState({allocations:[],expenses:[],statements:[],schools:[]});const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[search,setSearch]=useState('');
 async function load(){setLoading(true);setError('');try{setData(await api.getSchoolFinance(token));}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[token]);
 const values=useMemo(()=>{const authorized=data.allocations.reduce((s,i)=>s+Number(i.valor_alocado||0),0),executed=data.expenses.reduce((s,i)=>s+Number(i.valor||0),0),available=Math.max(0,authorized-executed);const pending=data.statements.filter(i=>!['Aprovada'].includes(i.status)).length;return{authorized,executed,available,pending,approved:data.statements.filter(i=>i.status==='Aprovada').length};},[data]);
 const categories=useMemo(()=>{const map=new Map();data.allocations.forEach(i=>{const key=i.categoria||'Outros';map.set(key,(map.get(key)||0)+Number(i.valor_alocado||0));});return[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6);},[data]);
 const schools=useMemo(()=>data.schools.map(s=>{const allocated=data.allocations.filter(i=>Number(i.escola_id)===Number(s.id)).reduce((n,i)=>n+Number(i.valor_alocado||0),0);return{...s,allocated};}).filter(i=>!search||i.nome.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.allocated-a.allocated).slice(0,5),[data,search]);
 const max=Math.max(1,...categories.map(i=>i[1]));
 return <div className="finance-shell"><Sidebar user={user} onLogout={onLogout} open={open} setOpen={setOpen}/><main className="finance-main" id="visao"><header className="finance-top"><div><h1>Setor Financeiro e Fiscal da Educação</h1><p>Acompanhe a execução orçamentária e a gestão fiscal da rede municipal de ensino.</p></div><div className="finance-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar unidade..."/></label><button aria-label="Notificações"><Bell/><b>{values.pending}</b></button><span>{user?.nome?.split(' ').map(i=>i[0]).slice(0,2).join('')}</span></div></header>
 {error&&<section className="finance-error"><AlertTriangle/><div><b>Não foi possível carregar os dados financeiros</b><p>{error}</p></div><button onClick={load}>Tentar novamente</button></section>}
 {loading?<div className="finance-loading">Carregando indicadores financeiros…</div>:<>
 <section className="finance-panel finance-shortcuts" id="atalhos"><h2>Acesso rápido aos módulos</h2><div>{[[CircleDollarSign,'Orçamento e Execução'],[ReceiptText,'Despesas'],[WalletCards,'Pagamentos'],[ClipboardCheck,'Prestação de Contas'],[Bus,'Transportes'],[ShieldCheck,'Auditorias'],[FileBarChart,'Relatórios Fiscais']].map(([Icon,label])=><a href={label==='Transportes'?'/transportes':'#execucao'} key={label}><Icon/><b>{label}</b></a>)}</div></section>
 <section className="finance-metrics"><Metric label="Orçamento autorizado" value={money(values.authorized)} detail="Recursos cadastrados" Icon={CircleDollarSign} tone="blue"/><Metric label="Executado" value={money(values.executed)} detail={`${values.authorized?((values.executed/values.authorized)*100).toFixed(1):0}% do orçamento`} Icon={ReceiptText} tone="green"/><Metric label="Prestações em análise" value={values.pending} detail="Aguardando avaliação" Icon={FileCheck2} tone="orange"/><Metric label="Prestações aprovadas" value={values.approved} detail="Registros homologados" Icon={CheckCircle2} tone="purple"/><Metric label="Saldo disponível" value={money(values.available)} detail={`${values.authorized?((values.available/values.authorized)*100).toFixed(1):0}% do orçamento`} Icon={WalletCards} tone="cyan"/></section>
 <section className="finance-grid" id="execucao"><article className="finance-panel wide"><header><div><h2>Execução orçamentária</h2><p>Distribuição real por categoria de recurso</p></div></header>{categories.length?<div className="finance-bars">{categories.map(([name,value],index)=><div key={name}><span>{name}</span><i><b style={{width:`${value/max*100}%`}} data-tone={index}/></i><strong>{short(value)}</strong></div>)}</div>:<p className="finance-empty">Nenhum orçamento cadastrado no período.</p>}</article><article className="finance-panel"><header><div><h2>Unidades com maior orçamento</h2><p>Consolidação da rede municipal</p></div></header>{schools.map((s,index)=><div className="finance-school" key={s.id}><span>{index+1}</span><div><b>{s.nome}</b><i><em style={{width:`${values.authorized?s.allocated/values.authorized*100:0}%`}}/></i></div><strong>{money(s.allocated)}</strong></div>)}{!schools.length&&<p className="finance-empty">Nenhuma unidade encontrada.</p>}</article></section>
 <section className="finance-bottom" id="prestacoes"><article className="finance-panel"><header><div><h2>Alertas e pendências</h2><p>Acompanhamento das obrigações registradas</p></div></header>{values.pending?<div className="finance-alert-row"><AlertTriangle/><div><b>{values.pending} prestação(ões) aguardando análise</b><small>Verifique os registros pendentes de avaliação fiscal.</small></div></div>:<div className="finance-alert-row ok"><CheckCircle2/><div><b>Nenhuma prestação pendente</b><small>Todos os registros estão atualizados.</small></div></div>}</article><article className="finance-panel" id="auditorias"><header><div><h2>Conformidade e fiscalização</h2><p>Controles aplicados aos registros financeiros</p></div></header><div className="finance-audit"><ShieldCheck/><div><b>Rastreabilidade ativa</b><small>Lançamentos financeiros preservam autoria, documento fiscal e histórico.</small></div><span>Ativo</span></div><div className="finance-audit"><FileCheck2/><div><b>LGPD e responsabilidade fiscal</b><small>Acesso restrito ao perfil financeiro municipal.</small></div><span>Protegido</span></div></article></section>
 </>}
 <footer className="finance-legal"><ShieldCheck/>As informações financeiras são confidenciais e seguem a Lei de Responsabilidade Fiscal (LRF) e a LGPD.</footer></main></div>;
}
