import React, { useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { api } from './services/api';
import IdebAnalysisPanel from './IdebAnalysisPanel';
import './gestao-municipal.css';

const emptyOverview={totals:{schools:0,students:0,classes:0,professors:0,employees:0},schools:[],ideb:[],demands:[],upcomingMeetings:0};
const iso=(value)=>value?new Date(value).toLocaleString('pt-BR'):'—';

export default function GestaoMunicipal({token,user,onLogout}){
 const location=useLocation();const navigate=useNavigate();const[tab,setTab]=useState(()=>new URLSearchParams(location.search).get('tab')||'indicadores');const[overview,setOverview]=useState(emptyOverview);const[schools,setSchools]=useState([]);const[ideb,setIdeb]=useState([]);const[idebAnalysis,setIdebAnalysis]=useState(null);const[meetings,setMeetings]=useState([]);const[demands,setDemands]=useState([]);const[error,setError]=useState('');const[msg,setMsg]=useState('');const[saving,setSaving]=useState(false);
 const[idebForm,setIdebForm]=useState({escolaId:'',ano:new Date().getFullYear()-1,etapa:'Anos iniciais',valor:'',meta:'',taxaAprovacao:'',aprendizadoPortugues:'',aprendizadoMatematica:'',fonte:'INEP/MEC',fonteUrl:'https://www.gov.br/inep/pt-br/areas-de-atuacao/pesquisas-estatisticas-e-indicadores/ideb'});
 const[meeting,setMeeting]=useState({titulo:'',tipo:'Reunião de gestão',escolaId:'',inicio:'',fim:'',local:'',linkVirtual:'',pauta:'',participantes:''});
 async function load(){try{setError('');const[o,s,i,a,m,d]=await Promise.all([api.getMunicipalOverview(token),api.listSchools(token),api.listIdeb(token),api.getIdebAnalysis(token),api.listMunicipalMeetings(token),api.listMunicipalDemands(token)]);setOverview(o||emptyOverview);setSchools(s||[]);setIdeb(i||[]);setIdebAnalysis(a||null);setMeetings(m||[]);setDemands(d||[]);setIdebForm(v=>({...v,escolaId:v.escolaId||s?.[0]?.id||''}));}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[token]);
 useEffect(()=>{const requested=new URLSearchParams(location.search).get('tab')||'indicadores';setTab(requested)},[location.search]);
 const pending=useMemo(()=>demands.filter(d=>d.status!=='Demanda resolvida').length,[demands]);
 function change(setter){return e=>setter(v=>({...v,[e.target.name]:e.target.value}))}
 async function perform(action,success){setSaving(true);setError('');setMsg('');try{await action();setMsg(success);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 function saveIdeb(e){e.preventDefault();const fields=['meta','taxaAprovacao','aprendizadoPortugues','aprendizadoMatematica'];const item={...idebForm,escolaId:Number(idebForm.escolaId),ano:Number(idebForm.ano),valor:Number(idebForm.valor)};fields.forEach(k=>item[k]=idebForm[k]===''?null:Number(idebForm[k]));perform(()=>api.importIdeb([item],token),'Resultado oficial do IDEB salvo e indicadores recalculados.');}
 function saveMeeting(e){e.preventDefault();perform(()=>api.createMunicipalMeeting({...meeting,escolaId:meeting.escolaId?Number(meeting.escolaId):null,inicio:new Date(meeting.inicio).toISOString(),fim:meeting.fim?new Date(meeting.fim).toISOString():null,linkVirtual:meeting.linkVirtual||null},token),'Reunião adicionada à agenda municipal.');}
 function report(type){perform(()=>api.downloadMunicipalReport(type,token),'Relatório oficial exportado em CSV.');}
 const tabs=[['indicadores','📊 Indicadores'],['ideb-analise','📈 Análise do IDEB'],['ideb','🎯 Gestão do IDEB'],['agenda','📅 Agenda'],['demandas','📌 Demandas'],['relatorios','📄 Relatórios']];
 return <main className="municipal-page"><header className="municipal-header"><div><small>SECRETARIA MUNICIPAL DE EDUCAÇÃO</small><h1>Gestão Municipal Integrada</h1><p>Indicadores oficiais, agenda, demandas e relatórios consolidados da rede.</p></div><div><Link to={user?.perfil==='Superintendente / Diretor de Ensino'?'/superintendencia':user?.perfil==='Coordenador Pedagógico Municipal'?'/coordenacao':'/gestor'}>← Voltar ao painel</Link><b>{user?.nome}</b><button onClick={onLogout}>Sair</button></div></header>
 <section className="municipal-ideb-highlight"><div><small>ANO LETIVO VIGENTE</small><strong>{idebAnalysis?.currentSchoolYear||new Date().getFullYear()}</strong><span>O ano vigente está destacado para acompanhamento; a nota mais recente é do ciclo oficial {idebAnalysis?.latestOfficialYear||2025}.</span></div><div>{idebAnalysis?.summaries?.map(item=><article key={item.stage}><small>{item.stage}</small><strong>{item.latestValue==null?'—':Number(item.latestValue).toFixed(1).replace('.',',')}</strong><span>IDEB {item.latestYear}</span></article>)}</div><button type="button" onClick={()=>setTab('ideb-analise')}>Abrir análise dos 10 anos →</button></section>
 <section className="municipal-summary">{[['Escolas',overview.totals.schools],['Alunos',overview.totals.students],['Funcionários',overview.totals.employees],['Reuniões futuras',overview.upcomingMeetings],['Demandas abertas',pending]].map(([l,v])=><article key={l}><span>{l}</span><strong>{Number(v||0).toLocaleString('pt-BR')}</strong></article>)}</section>
 <nav className="municipal-tabs">{tabs.map(([v,l])=><button className={tab===v?'active':''} onClick={()=>navigate(`/gestao-municipal?tab=${v}`)} key={v}>{l}</button>)}</nav>{error&&<p className="municipal-feedback error">{error}</p>}{msg&&<p className="municipal-feedback success">{msg}</p>}
 {tab==='indicadores'&&<section className="municipal-card"><h2>Indicadores consolidados por escola</h2><p>Dados calculados diretamente de matrículas, turmas, vínculos, diário, notas e resultados oficiais do IDEB.</p><div className="municipal-table"><table><thead><tr><th>Escola</th><th>Alunos</th><th>Turmas</th><th>Professores</th><th>Funcionários</th><th>Frequência</th><th>Média</th><th>IDEB/meta</th></tr></thead><tbody>{overview.schools.map(s=><tr key={s.id}><td><b>{s.nome}</b><small>{s.codigoInep||'INEP não informado'}</small></td><td>{s.alunos}</td><td>{s.turmas}</td><td>{s.professores}</td><td>{s.funcionarios}</td><td>{Number(s.frequencia).toFixed(1)}%</td><td>{Number(s.media).toFixed(1)}</td><td>{s.ideb??'—'} / {s.idebMeta??'—'}<small>{s.idebAno||''} {s.idebEtapa||''}</small></td></tr>)}</tbody></table></div></section>}
 {tab==='ideb-analise'&&<IdebAnalysisPanel analysis={idebAnalysis}/>}
 {tab==='ideb'&&<><form className="municipal-card municipal-form" onSubmit={saveIdeb}><h2>Importar resultado oficial do IDEB</h2><label>Escola<select name="escolaId" value={idebForm.escolaId} onChange={change(setIdebForm)} required>{schools.map(s=><option value={s.id} key={s.id}>{s.nome}</option>)}</select></label><label>Ano<input type="number" name="ano" value={idebForm.ano} onChange={change(setIdebForm)} required/></label><label>Etapa<select name="etapa" value={idebForm.etapa} onChange={change(setIdebForm)}><option>Anos iniciais</option><option>Anos finais</option><option>Ensino médio</option></select></label><label>IDEB<input type="number" min="0" max="10" step="0.1" name="valor" value={idebForm.valor} onChange={change(setIdebForm)} required/></label><label>Meta<input type="number" min="0" max="10" step="0.1" name="meta" value={idebForm.meta} onChange={change(setIdebForm)}/></label><label>Taxa de aprovação (%)<input type="number" min="0" max="100" step="0.01" name="taxaAprovacao" value={idebForm.taxaAprovacao} onChange={change(setIdebForm)}/></label><label>Aprendizado — Português<input type="number" min="0" step="0.01" name="aprendizadoPortugues" value={idebForm.aprendizadoPortugues} onChange={change(setIdebForm)}/></label><label>Aprendizado — Matemática<input type="number" min="0" step="0.01" name="aprendizadoMatematica" value={idebForm.aprendizadoMatematica} onChange={change(setIdebForm)}/></label><label className="wide">Fonte oficial<input name="fonteUrl" type="url" value={idebForm.fonteUrl} onChange={change(setIdebForm)} required/></label><button disabled={saving}>Salvar resultado oficial</button></form><section className="municipal-card"><h2>Série histórica</h2><div className="municipal-table"><table><thead><tr><th>Ano</th><th>Escola</th><th>Etapa</th><th>Resultado</th><th>Meta</th><th>Fonte</th></tr></thead><tbody>{ideb.map(i=><tr key={i.id}><td>{i.ano}</td><td>{i.escola||'Rede municipal'}</td><td>{i.etapa}</td><td><b>{i.valor}</b></td><td>{i.meta??'—'}</td><td>{i.fonteUrl?<a href={i.fonteUrl} target="_blank" rel="noreferrer">{i.fonte}</a>:i.fonte}</td></tr>)}</tbody></table></div></section></>}
 {tab==='agenda'&&<><form className="municipal-card municipal-form" onSubmit={saveMeeting}><h2>Agendar reunião municipal</h2><label>Título<input name="titulo" value={meeting.titulo} onChange={change(setMeeting)} required/></label><label>Tipo<select name="tipo" value={meeting.tipo} onChange={change(setMeeting)}><option>Reunião de gestão</option><option>Conselho de diretores</option><option>Formação pedagógica</option><option>Prestação de contas</option></select></label><label>Escola<select name="escolaId" value={meeting.escolaId} onChange={change(setMeeting)}><option value="">Toda a rede</option>{schools.map(s=><option value={s.id} key={s.id}>{s.nome}</option>)}</select></label><label>Início<input type="datetime-local" name="inicio" value={meeting.inicio} onChange={change(setMeeting)} required/></label><label>Fim<input type="datetime-local" name="fim" value={meeting.fim} onChange={change(setMeeting)}/></label><label>Local<input name="local" value={meeting.local} onChange={change(setMeeting)}/></label><label>Link virtual<input type="url" name="linkVirtual" value={meeting.linkVirtual} onChange={change(setMeeting)}/></label><label>Participantes<input name="participantes" value={meeting.participantes} onChange={change(setMeeting)}/></label><label className="wide">Pauta<textarea name="pauta" value={meeting.pauta} onChange={change(setMeeting)} required/></label><button disabled={saving}>Agendar reunião</button></form><section className="municipal-grid">{meetings.map(m=><article className="municipal-card" key={m.id}><small>{m.tipo} · {m.status}</small><h3>{m.titulo}</h3><p><b>{iso(m.inicio)}</b><br/>{m.escola||'Toda a rede'} · {m.local||'Local a definir'}</p><p>{m.pauta}</p>{m.status==='Agendada'&&<div><button onClick={()=>perform(()=>api.updateMunicipalMeetingStatus(m.id,'Realizada',token),'Reunião marcada como realizada.')}>Concluir</button> <button className="danger" onClick={()=>perform(()=>api.updateMunicipalMeetingStatus(m.id,'Cancelada',token),'Reunião cancelada.')}>Cancelar</button></div>}</article>)}</section></>}
 {tab==='demandas'&&<section className="municipal-card"><h2>Solicitações e Demandas</h2><p>O novo fluxo separa as responsabilidades: a Direção Escolar registra a necessidade, a Secretaria de Educação decide e a Secretaria Administrativa executa as tarefas autorizadas.</p><div className="municipal-summary"><article><span>Demandas visíveis</span><strong>{demands.length}</strong></article><article><span>Em acompanhamento</span><strong>{pending}</strong></article><article><span>Resolvidas</span><strong>{demands.length-pending}</strong></article></div><Link className="municipal-primary-link" to="/gestor/demandas">Abrir fluxo completo de solicitações →</Link></section>}
 {tab==='relatorios'&&<section className="municipal-card"><h2>Relatórios oficiais para exportação</h2><p>Arquivos CSV em UTF-8, com dados atuais do banco e emissão registrada na auditoria.</p><div className="report-grid">{[['indicadores','Indicadores consolidados'],['ideb','Série histórica do IDEB'],['funcionarios','Funcionários e vínculos'],['transporte','Transporte escolar'],['financeiro','Execução financeira'],['demandas','Demandas municipais'],['reunioes','Agenda municipal']].map(([type,label])=><button key={type} onClick={()=>report(type)} disabled={saving}><span>⬇️</span><b>{label}</b><small>Exportar CSV oficial</small></button>)}</div></section>}
 </main>;
}
