import React,{useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {api} from './services/api';
const card={background:'#fff',borderRadius:14,padding:20,boxShadow:'0 3px 14px #dce5f080'};
export default function ProfessorTurmas({token,user}){
 const {turmaId,alunoId}=useParams(); const [dashboard,setDashboard]=useState({turmas:[]}); const [students,setStudents]=useState([]); const [history,setHistory]=useState(null); const [error,setError]=useState('');
 useEffect(()=>{api.getProfessorDashboard(token).then(setDashboard).catch(e=>setError(e.message));},[token]);
 useEffect(()=>{if(turmaId)api.getProfessorClassStudents(turmaId,token).then(setStudents).catch(e=>setError(e.message));},[turmaId,token]);
 useEffect(()=>{if(turmaId&&alunoId)api.getProfessorStudentHistory(alunoId,turmaId,token).then(setHistory).catch(e=>setError(e.message));},[turmaId,alunoId,token]);
 const turma=dashboard.turmas.find(t=>String(t.id)===String(turmaId));
 return <div style={{minHeight:'100vh',background:'#f4f7fc',color:'#09245a',fontFamily:'Arial'}}>
  <header style={{background:'#fff',padding:'18px 5%',display:'flex',gap:20,alignItems:'center',borderBottom:'1px solid #dce5f0'}}><Link to="/professor">← Portal do Professor</Link><b style={{fontSize:22}}>👥 Minhas Turmas</b><span style={{marginLeft:'auto'}}>{user?.nome}</span></header>
  <main style={{maxWidth:1200,margin:'auto',padding:'30px 5%'}}>
   {error&&<p style={{background:'#fee',color:'#a22',padding:12}}>{error}</p>}
   {!turmaId&&<><h1>Turmas em que leciono</h1><p>Somente vínculos ativos atribuídos ao seu cadastro docente.</p><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:16}}>{dashboard.turmas.map(t=><Link key={t.id} to={`/professor/turmas/${t.id}`} style={{...card,textDecoration:'none',color:'#09245a'}}><span style={{fontSize:30}}>🏫</span><h2>{t.nome}</h2><p>{t.componenteCurricular||'Disciplina não informada'}</p><small>{t.turno} · {t.alunosMatriculados} alunos · Sala {t.sala||'-'}</small><b style={{display:'block',color:'#176fe3',marginTop:16}}>Abrir turma →</b></Link>)}</section>{!dashboard.turmas.length&&<p style={card}>Nenhuma turma atribuída.</p>}</>}
   {turmaId&&!alunoId&&<><p><Link to="/professor/turmas">← Todas as turmas</Link></p><h1>{turma?.nome||'Turma'}</h1><p>{turma?.componenteCurricular} · Lista de alunos matriculados</p><section style={card}>{students.map((s,i)=><Link key={s.id} to={`/professor/turmas/${turmaId}/alunos/${s.id}`} style={{display:'flex',alignItems:'center',gap:14,padding:14,borderBottom:'1px solid #edf1f7',textDecoration:'none',color:'#09245a'}}><span style={{background:'#176fe3',color:'#fff',borderRadius:'50%',padding:12}}>{String(i+1).padStart(2,'0')}</span><span><b>{s.nomeSocial||s.nome}</b><small style={{display:'block'}}>Matrícula {s.matriculaId} · {s.status}</small></span><b style={{marginLeft:'auto',color:'#176fe3'}}>Ver histórico →</b></Link>)}{!students.length&&<p>Nenhum aluno matriculado nesta turma.</p>}</section></>}
   {turmaId&&alunoId&&<><p><Link to={`/professor/turmas/${turmaId}`}>← Lista de alunos</Link></p><h1>Histórico do aluno</h1>{history&&<><section style={{...card,display:'flex',gap:30,flexWrap:'wrap'}}><div><small>ALUNO</small><h2>{history.aluno?.nomeSocial||history.aluno?.nome}</h2></div><div><small>MÉDIA</small><h2>{history.resumo.media==null?'Sem notas':Number(history.resumo.media).toFixed(1)}</h2></div><div><small>FALTAS</small><h2 style={{color:history.resumo.totalFaltas?'#c62828':'#16864b'}}>{history.resumo.totalFaltas}</h2></div><div><small>ATIVIDADES PENDENTES</small><h2 style={{color:history.resumo.pendencias?'#c62828':'#16864b'}}>{history.resumo.pendencias}</h2></div></section><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,marginTop:18}}><article style={card}><h2>📝 Notas</h2>{history.notas.map((n,i)=><p key={i}><b>{n.avaliacao}</b><span style={{float:'right'}}>{Number(n.nota).toFixed(1)}</span><br/><small>{n.disciplina} · {new Date(n.data).toLocaleDateString('pt-BR')}</small></p>)}{!history.notas.length&&<p>Nenhuma nota lançada.</p>}</article><article style={card}><h2>📅 Faltas</h2>{history.faltas.map((f,i)=><p key={i}><b>{new Date(f.data).toLocaleDateString('pt-BR')}</b><span style={{float:'right'}}>{f.quantidade} falta(s)</span><br/><small>{f.disciplina} · {f.justificada?'Justificada':'Não justificada'}</small></p>)}{!history.faltas.length&&<p>Nenhuma falta registrada.</p>}</article><article style={card}><h2>⏳ Atividades</h2>{history.atividades.map((a,i)=><p key={i}><b>{a.titulo}</b><span style={{float:'right',color:a.status==='Pendente'||a.status==='Atrasada'?'#c62828':'#16864b'}}>{a.status}</span><br/><small>Prazo: {new Date(a.prazo).toLocaleDateString('pt-BR')}</small></p>)}{!history.atividades.length&&<p>Nenhuma atividade pendente.</p>}</article></section></>}</>}
  </main>
 </div>;
}
