import React,{useEffect,useState} from 'react';import{Link}from'react-router-dom';import{api}from'./services/api';
const box={background:'#fff',padding:20,borderRadius:14,boxShadow:'0 3px 15px #dce5f080'};
export default function ProfessorNotas({token,user}){const[data,setData]=useState({turmas:[]});const[classId,setClassId]=useState('');const[book,setBook]=useState({alunos:[],avaliacoes:[],notas:[],mediaAprovacao:6});const[grades,setGrades]=useState({});const[msg,setMsg]=useState('');const[error,setError]=useState('');const[form,setForm]=useState({titulo:'',tipo:'Atividade',data:new Date().toISOString().slice(0,10),valorMaximo:2,bimestre:1});
useEffect(()=>{api.getProfessorDashboard(token).then(setData).catch(e=>setError(e.message));},[token]);
async function load(id){if(!id)return;try{const b=await api.getProfessorGradebook(id,token);setBook(b);const g={};b.notas.forEach(n=>g[n.alunoId+'-'+n.avaliacaoId]=n.pontos);setGrades(g);}catch(e){setError(e.message);}}
async function add(e){e.preventDefault();try{await api.createProfessorAssessment(classId,form,token);setMsg('Atividade adicionada ao bimestre.');setForm({...form,titulo:''});await load(classId);}catch(e){setError(e.message);}}
async function save(){try{const notas=Object.entries(grades).map(([key,pontos])=>{const[a,v]=key.split('-');return{alunoId:Number(a),avaliacaoId:Number(v),pontos:Number(pontos||0)}});await api.saveProfessorGrades(classId,notas,token);setMsg('Notas salvas e médias recalculadas.');await load(classId);}catch(e){setError(e.message);}}
const totalMax=book.avaliacoes.reduce((s,a)=>s+Number(a.valorMaximo),0);const studentTotal=id=>book.avaliacoes.reduce((s,a)=>s+Number(grades[id+'-'+a.id]||0),0);
return <div style={{minHeight:'100vh',background:'#f4f7fc',color:'#09245a',fontFamily:'Arial'}}><header style={{background:'#fff',padding:'18px 5%',display:'flex',gap:20}}><Link to="/professor">← Portal do Professor</Link><b style={{fontSize:22}}>✅ Lançar Notas</b><span style={{marginLeft:'auto'}}>{user?.nome}</span></header><main style={{maxWidth:1400,margin:'auto',padding:'28px 4%'}}><h1>Notas, atividades e média do aluno</h1><p>A média mínima para aprovação é <b>6,0</b>. Cada bimestre aceita atividades que somem até 10 pontos.</p>{msg&&<p style={{background:'#e5f7ec',color:'#165f3c',padding:12}}>{msg}</p>}{error&&<p style={{background:'#fee',color:'#a22',padding:12}}>{error}</p>}
<section style={{display:'grid',gridTemplateColumns:'1fr 2fr',gap:18}}><article style={box}><h2>Turma e atividades</h2><label>Turma<select value={classId} onChange={e=>{setClassId(e.target.value);load(e.target.value)}} style={{display:'block',width:'100%',padding:10,margin:'6px 0 18px'}}><option value="">Selecione</option>{data.turmas.map(t=><option key={t.id} value={t.id}>{t.nome} — {t.componenteCurricular}</option>)}</select></label>{classId&&<form onSubmit={add}><h3>Dividir nota em atividades</h3><input required placeholder="Nome da atividade" value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} style={{width:'100%',padding:10,marginBottom:8}}/><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} style={{width:'100%',padding:10,marginBottom:8}}><option>Atividade</option><option>Trabalho</option><option>Prova</option><option>Seminário</option><option>Participação</option></select><input type="date" required value={form.data} onChange={e=>setForm({...form,data:e.target.value})} style={{width:'100%',padding:10,marginBottom:8}}/><label>Valor da atividade<input type="number" min=".1" max="10" step=".1" value={form.valorMaximo} onChange={e=>setForm({...form,valorMaximo:e.target.value})} style={{width:'100%',padding:10,margin:'6px 0'}}/></label><button style={{padding:11,background:'#176fe3',color:'#fff',border:0,borderRadius:8}}>＋ Adicionar atividade</button></form>}<p><b>Pontos distribuídos:</b> {totalMax.toFixed(1)} / 10,0</p><p><b>Restam para distribuir:</b> {(10-totalMax).toFixed(1)} pontos</p></article>
<article style={box}><h2>Boletim da turma</h2>{!classId&&<p>Selecione uma turma.</p>}{classId&&<div style={{overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left'}}>Aluno</th>{book.avaliacoes.map(a=><th key={a.id}>{a.titulo}<small style={{display:'block'}}>Vale {a.valorMaximo}</small></th>)}<th>Média</th><th>Precisa</th><th>Faltam</th><th>Situação</th></tr></thead><tbody>{book.alunos.map(al=>{const total=studentTotal(al.id);const falta=Math.max(0,book.mediaAprovacao-total);return <tr key={al.id}><td style={{padding:10,borderTop:'1px solid #edf1f7'}}><b>{al.nome}</b></td>{book.avaliacoes.map(a=><td key={a.id} style={{padding:8,borderTop:'1px solid #edf1f7'}}><input aria-label={al.nome+' - '+a.titulo} type="number" min="0" max={a.valorMaximo} step=".1" value={grades[al.id+'-'+a.id]??''} onChange={e=>setGrades({...grades,[al.id+'-'+a.id]:e.target.value})} style={{width:65,padding:7}}/></td>)}<td><b>{total.toFixed(1)}</b></td><td>{book.mediaAprovacao.toFixed(1)}</td><td style={{color:falta?'#c62828':'#16864b'}}><b>{falta.toFixed(1)}</b></td><td><span style={{background:total>=book.mediaAprovacao?'#dff5e7':'#ffe5e5',color:total>=book.mediaAprovacao?'#16864b':'#c62828',padding:'6px 9px',borderRadius:12}}>{total>=book.mediaAprovacao?'Aprovado':'Em recuperação'}</span></td></tr>})}</tbody></table>{book.avaliacoes.length>0&&<button onClick={save} style={{marginTop:16,padding:12,background:'#0aa56c',color:'#fff',border:0,borderRadius:8,fontWeight:700}}>💾 Salvar notas</button>}</div>}</article></section></main></div>}
