import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './services/api';

const card = { background: '#fff', padding: 22, borderRadius: 14, boxShadow: '0 3px 16px #dce5f080' };
const input = { display: 'block', width: '100%', boxSizing: 'border-box', padding: 10, marginTop: 5, border: '1px solid #b8c8de', borderRadius: 7 };

export default function ProfessorPerfil({ token, user }) {
  const [profile, setProfile] = useState({ nome: '', email: '', emailPessoal: '', telefone: '', whatsapp: '', biografia: '', tema: 'claro', corDestaque: '#176fe3', notificacoesEmail: true, notificacoesWhatsapp: false, foto: null });
  const [password, setPassword] = useState({ atual: '', nova: '', confirmar: '' });
  const [history, setHistory] = useState([]);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  async function load() { try { const [data, changes] = await Promise.all([api.getProfessorProfile(token), api.getProfessorHistory(token)]); setProfile(data); setHistory(changes); } catch (requestError) { setError(requestError.message); } }
  useEffect(() => { load(); }, [token]);

  async function save(event) { event.preventDefault(); try { await api.updateProfessorProfile(profile, token); setMessage('Perfil e preferências atualizados.'); await load(); } catch (requestError) { setError(requestError.message); } }
  function choosePhoto(event) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 2000000) { setError('A foto deve ter no máximo 2 MB.'); return; } const reader = new FileReader(); reader.onload = () => setProfile((current) => ({ ...current, foto: String(reader.result) })); reader.readAsDataURL(file); }
  async function savePhoto() { try { await api.updateProfessorPhoto(profile.foto, token); setMessage('Foto atualizada.'); await load(); } catch (requestError) { setError(requestError.message); } }
  async function removePhoto() { try { await api.deleteProfessorPhoto(token); setMessage('Foto removida.'); await load(); } catch (requestError) { setError(requestError.message); } }
  async function changePassword(event) { event.preventDefault(); if (password.nova.length < 8 || password.nova !== password.confirmar) { setError('A nova senha deve ter ao menos 8 caracteres e coincidir com a confirmação.'); return; } try { await api.changePassword(password.atual, password.nova, token); setPassword({ atual: '', nova: '', confirmar: '' }); setMessage('Senha alterada com segurança.'); } catch (requestError) { setError(requestError.message); } }
  const set = (field, value) => setProfile((current) => ({ ...current, [field]: value }));

  return <div style={{ minHeight: '100vh', background: '#f4f7fc', color: '#09245a', fontFamily: 'Arial' }}><header style={{ background: '#fff', padding: '14px 4%', display: 'flex', alignItems: 'center', gap: 16 }}><b style={{ fontSize: 23 }}>⚙️ Meu perfil profissional</b><Link to="/professor" style={{ marginLeft: 'auto' }}>← Portal do Professor</Link></header><main style={{ maxWidth: 1180, margin: 'auto', padding: '28px 4%' }}><h1>Configurações e personalização</h1><p>Professor(a): <b>{user?.nome}</b>. Seus dados profissionais, contatos e segurança ficam centralizados aqui.</p>{message && <p style={{ background: '#e5f7ec', color: '#16613d', padding: 12 }}>{message}</p>}{error && <p style={{ background: '#fee', color: '#a22', padding: 12 }}>{error}</p>}
    <section style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 18 }}><article style={card}><h2>Foto</h2><div style={{ width: 160, height: 160, borderRadius: '50%', overflow: 'hidden', background: '#e5edf8', display: 'grid', placeItems: 'center', fontSize: 54 }}>{profile.foto ? <img src={profile.foto} alt="Foto do professor" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : '👤'}</div><input type="file" accept="image/*" onChange={choosePhoto} style={{ ...input, marginTop: 14 }} /><div style={{ display: 'flex', gap: 8, marginTop: 10 }}><button type="button" onClick={savePhoto} disabled={!profile.foto}>Salvar foto</button>{profile.foto && <button type="button" onClick={removePhoto}>Remover</button>}</div></article>
      <form onSubmit={save} style={card}><h2>Dados e contatos</h2><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}><label>Nome completo<input value={profile.nome || ''} onChange={(event) => set('nome', event.target.value)} style={input} /></label><label>E-mail institucional<input type="email" value={profile.email || ''} onChange={(event) => set('email', event.target.value)} style={input} /></label><label>E-mail pessoal<input type="email" value={profile.emailPessoal || ''} onChange={(event) => set('emailPessoal', event.target.value)} style={input} /></label><label>Telefone<input value={profile.telefone || ''} onChange={(event) => set('telefone', event.target.value)} style={input} /></label><label>WhatsApp<input value={profile.whatsapp || ''} onChange={(event) => set('whatsapp', event.target.value)} style={input} /></label><label>Especialidade<input value={profile.especialidade || ''} disabled style={input} /></label></div><label>Biografia profissional<textarea rows="4" value={profile.biografia || ''} onChange={(event) => set('biografia', event.target.value)} style={input} /></label><h3>Personalização</h3><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}><label>Tema<select value={profile.tema || 'claro'} onChange={(event) => set('tema', event.target.value)} style={input}><option value="claro">Claro</option><option value="escuro">Escuro</option><option value="sistema">Seguir dispositivo</option></select></label><label>Cor de destaque<input type="color" value={profile.corDestaque || '#176fe3'} onChange={(event) => set('corDestaque', event.target.value)} style={input} /></label></div><p><label><input type="checkbox" checked={profile.notificacoesEmail !== false} onChange={(event) => set('notificacoesEmail', event.target.checked)} /> Receber avisos por e-mail</label> &nbsp; <label><input type="checkbox" checked={Boolean(profile.notificacoesWhatsapp)} onChange={(event) => set('notificacoesWhatsapp', event.target.checked)} /> Receber avisos por WhatsApp</label></p><button style={{ background: profile.corDestaque || '#176fe3', color: '#fff', border: 0, padding: '11px 18px', borderRadius: 7 }}>Salvar perfil</button></form></section>
    <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginTop: 18 }}><form onSubmit={changePassword} style={card}><h2>🔐 Alterar senha</h2><label>Senha atual<input type="password" required value={password.atual} onChange={(event) => setPassword({ ...password, atual: event.target.value })} style={input} /></label><label>Nova senha<input type="password" required value={password.nova} onChange={(event) => setPassword({ ...password, nova: event.target.value })} style={input} /></label><label>Confirmar nova senha<input type="password" required value={password.confirmar} onChange={(event) => setPassword({ ...password, confirmar: event.target.value })} style={input} /></label><button style={{ marginTop: 12 }}>Alterar senha</button></form><article style={{ ...card, maxHeight: 430, overflow: 'auto' }}><h2>🕘 Histórico de alterações</h2>{history.map((item) => <p key={item.id} style={{ borderTop: '1px solid #e4ebf5', paddingTop: 9 }}><b>{item.acao} · {item.entidade}</b><br /><small>{new Date(item.criadoEm).toLocaleString('pt-BR')} · registro {item.registroId || '—'}</small></p>)}{!history.length && <p>Nenhuma alteração registrada.</p>}</article></section>
  </main></div>;
}
