import React,{useEffect,useState}from'react';
import{Link}from'react-router-dom';
import{api}from'./services/api';
const card={background:'#fff',padding:20,borderRadius:14,boxShadow:'0 3px 15px #dce5f080'};
const tone=v=>v>=8?'#138a52':v>=6?'#e28b0a':'#c93636';
export default function ProfessorRelatorios({token}){
 const[classes,setClasses]=useState([]),[classId,setClassId]=useState(''),[detail,setDetail]=useState({alunos:[],competencias:[]}),[student,setStudent]=useState(null),[error,setError]=useState('');
 useEffect(()=>{api.getProfessorClassReports(token).then(setClasses).catch(e=>setError(e.message))},[token]);
 async function selectClass(id){setClassId(id);setStudent(null);try{setDetail(await api.getProfessorClassReport(id,token))}catch(e){setError(e.message)}}
 async function selectStudent(id){try{setStudent(await api.getProfessorStudentReport(id,classId,token))}catch(e){setError(e.message)}}
 const chosen=classes.find(x=>String(x.id)===String(classId));
 return <div style={{minHeight:'100vh',background:'#f4f7fc',color:'#09245a',fontFamily:'Arial'}}>
  <style>{`@media print{.no-print{display:none!important}body{background:#fff}.report-print{box-shadow:none!important}@page{size:A4;margin:14mm}}`}</style>
  <header className="no-print" style={{background:'#fff',padding:'12px 4%',display:'flex',alignItems:'center',gap:18,borderBottom:'1px solid #dce5f0'}}><img src="/images/prefeitura.png" alt="Prefeitura Municipal de Pindobaçu" style={{width:78,height:62,objectFit:'contain'}}/><div><b style={{fontSize:22}}>Relatórios Pedagógicos — SIEDU</b><small style={{display:'block'}}>Acompanhamento do ensino e da aprendizagem</small></div><Link to="/professor" style={{marginLeft:'auto'}}>← Portal do Professor</Link></header>
  <main style={{maxWidth:1320,margin:'auto',padding:'28px 4%'}}><div style={{display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1>📊 Desempenho e competências</h1><p>Avalie turmas, acompanhe cada aluno e identifique intervenções pedagógicas necessárias.</p></div><button className="no-print" onClick={()=>window.print()} style={{marginLeft:'auto'}}>🖨️ Imprimir relatório atual</button></div>{error&&<p style={{background:'#fee',color:'#a22',padding:12}}>{error}</p>}
  <h2>Visão geral das turmas</h2><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:14}}>{classes.map(c=><button key={c.id} onClick={()=>selectClass(c.id)} style={{...card,border:String(c.id)===String(classId)?'3px solid #176fe3':'1px solid transparent',textAlign:'left',color:'#09245a'}}><h3>{c.nome}</h3><p>{c.disciplina} · {c.turno}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><span>👥 <b>{c.alunos}</b><small style={{display:'block'}}>alunos</small></span><span style={{color:tone(c.media)}}>📈 <b>{c.media}</b><small style={{display:'block'}}>média</small></span><span style={{color:c.frequencia>=75?'#138a52':'#c93636'}}>✅ <b>{c.frequencia}%</b><small style={{display:'block'}}>frequência</small></span><span>📝 <b>{c.atividades}</b><small style={{display:'block'}}>atividades</small></span></div></button>)}</section>
  {chosen&&<section className="report-print" style={{...card,marginTop:20}}><div style={{display:'flex',alignItems:'center',gap:14}}><img src="/images/prefeitura.png" alt="" style={{width:65,height:50,objectFit:'contain'}}/><div><h2 style={{margin:0}}>Relatório da turma — {chosen.nome}</h2><p>{chosen.disciplina} · {chosen.turno} · Sala {chosen.sala||'-'}</p></div></div>
   <h3>Desempenho individual</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:10}}>Aluno</th><th>Média</th><th>Frequência</th><th>Pendências</th><th className="no-print">Ação</th></tr></thead><tbody>{detail.alunos.map(a=><tr key={a.id} style={{borderTop:'1px solid #dce5f0'}}><td style={{padding:10}}>{a.nome}</td><td style={{textAlign:'center',color:tone(a.media),fontWeight:700}}>{a.media}</td><td style={{textAlign:'center',color:a.frequencia>=75?'#138a52':'#c93636'}}>{a.frequencia}%</td><td style={{textAlign:'center'}}>{a.pendencias}</td><td className="no-print" style={{textAlign:'center'}}><button onClick={()=>selectStudent(a.id)}>Ver relatório individual</button></td></tr>)}</tbody></table></div>
   <h3>Competências exigidas pelas atividades</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12}}>{detail.competencias.map(c=><article key={c.competencia} style={{background:'#eef5ff',padding:14,borderRadius:10}}><b>🎯 {c.competencia}</b><p>{c.atividadesExigem} atividade(s)</p><small>{c.atividades.join(' · ')}</small></article>)}{!detail.competencias.length&&<p>Nenhuma competência vinculada às atividades desta turma.</p>}</div>
  </section>}
  {student&&<section className="report-print" style={{...card,marginTop:20,borderTop:'5px solid #176fe3'}}><h2>👤 Relatório individual — {student.nome}</h2><p><b>Turma:</b> {student.turma} · <b>Disciplina:</b> {student.disciplina}</p><div style={{display:'flex',gap:16,flexWrap:'wrap'}}><div style={{...card,boxShadow:'none',background:'#f4f7fc'}}><small>Média</small><h2 style={{color:tone(student.media)}}>{student.media}</h2></div><div style={{...card,boxShadow:'none',background:'#f4f7fc'}}><small>Frequência</small><h2>{student.frequencia.frequencia}%</h2></div><div style={{...card,boxShadow:'none',background:'#f4f7fc'}}><small>Faltas</small><h2>{student.frequencia.faltas}</h2></div></div>
   <h3>Notas e avaliações</h3>{student.notas.map(n=><p key={n.titulo+n.data} style={{borderBottom:'1px solid #dce5f0',paddingBottom:8}}><b>{n.titulo}</b> — {n.pontos}/{n.valorMaximo} ponto(s) · Nota proporcional: <b style={{color:tone(n.nota)}}>{n.nota}</b></p>)}{!student.notas.length&&<p>Sem notas lançadas.</p>}
   <h3>Relatório de competências</h3>{student.competencias.map(c=><div key={c.competencia} style={{borderLeft:'4px solid '+(c.nivelEstimado==='Consolidada'?'#138a52':c.nivelEstimado==='Em desenvolvimento'?'#e28b0a':'#c93636'),padding:'8px 12px',marginBottom:10}}><b>{c.competencia}</b><span style={{float:'right'}}>{c.nivelEstimado}</span><small style={{display:'block',marginTop:5}}>Exigida em: {c.atividades.join(', ')}</small></div>)}<p style={{fontSize:12,color:'#607399'}}>O nível de competência é um indicador pedagógico estimado a partir do desempenho registrado e deve ser complementado pela observação do professor.</p>
  </section>}
  </main></div>
}
