import React,{useEffect,useState}from'react';import{Link}from'react-router-dom';import{api}from'./services/api';
const colors={'Rascunho':['#eef2f7','#52657f'],'Enviado para aprovação':['#fff3d8','#9a6500'],'Aprovado':['#ddf6e7','#147542'],'Correção solicitada':['#ffe2e2','#b42323']};const box={background:'#fff',borderRadius:14,padding:20,boxShadow:'0 3px 15px #dce5f080'};
export default function ProfessorPlanos({token,user}){const[plans,setPlans]=useState([]);const[filter,setFilter]=useState('Todos');const[selected,setSelected]=useState(null);const[msg,setMsg]=useState('');const[error,setError]=useState('');async function load(){try{setPlans(await api.listProfessorLessonPlans(token))}catch(e){setError(e.message)}}useEffect(()=>{load()},[token]);
async function submit(plan){try{await api.updateProfessorLessonPlan(plan.id,{...plan,data:String(plan.data).slice(0,10),status:'Enviado para aprovação'},token);setMsg('Plano enviado para aprovação da Coordenação Pedagógica.');setSelected(null);await load()}catch(e){setError(e.message)}}
const statusOf=p=>p.status==='Enviado para aprovação'?'Aprovação pendente':p.status;const list=filter==='Todos'?plans:plans.filter(p=>statusOf(p)===filter);const count=s=>plans.filter(p=>statusOf(p)===s).length;
return <div style={{minHeight:'100vh',background:'#f4f7fc',color:'#09245a',fontFamily:'Arial'}}><header style={{background:'#fff',padding:'12px 4%',display:'flex',alignItems:'center',gap:18,borderBottom:'1px solid #dce5f0'}}><img src="/images/prefeitura.png" alt="Prefeitura Municipal de Pindobaçu" style={{width:78,height:62,objectFit:'contain'}}/><div><b style={{fontSize:22}}>Planos de Aula — SIEDU</b><small style={{display:'block'}}>Documentos para acompanhamento e aprovação pedagógica</small></div><Link to="/professor" style={{marginLeft:'auto'}}>← Portal do Professor</Link></header><main style={{maxWidth:1300,margin:'auto',padding:'28px 4%'}}><h1>📋 Meus Planos de Aula</h1><p>Finalize seus planejamentos, envie para aprovação e acompanhe devoluções ou aprovações.</p>{msg&&<p style={{background:'#e5f7ec',color:'#16613d',padding:12}}>{msg}</p>}{error&&<p style={{background:'#fee',color:'#a22',padding:12}}>{error}</p>}
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:13,margin:'20px 0'}}>{[['Todos',plans.length,'📚'],['Rascunho',count('Rascunho'),'✏️'],['Aprovação pendente',count('Aprovação pendente'),'⏳'],['Aprovado',count('Aprovado'),'✅'],['Correção solicitada',count('Correção solicitada'),'🔄']].map(([s,n,i])=><button key={s} onClick={()=>setFilter(s)} style={{...box,border:filter===s?'2px solid #176fe3':'2px solid transparent',textAlign:'left',color:'#09245a'}}><span style={{fontSize:25}}>{i}</span><b style={{display:'block',marginTop:8}}>{s}</b><strong style={{fontSize:25}}>{n}</strong></button>)}</section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:16}}>{list.map(p=>{const raw=p.status;const status=statusOf(p);const palette=colors[raw]||colors.Rascunho;return <article key={p.id} style={box}><span style={{background:palette[0],color:palette[1],padding:'7px 10px',borderRadius:14,fontWeight:700}}>{status}</span><h2>{p.tema}</h2><p><b>{p.turma}</b> · {p.disciplina}</p><p>{new Date(p.data).toLocaleDateString('pt-BR')} · {p.bimestre}º bimestre · {p.quantidadeAulas} aula(s)</p><small>Objetivos: {p.objetivos}</small><div style={{display:'flex',gap:8,marginTop:16,flexWrap:'wrap'}}><button onClick={()=>setSelected(p)}>👁️ Ver plano</button>{(raw==='Rascunho'||raw==='Correção solicitada')&&<><Link to="/professor/planejamento" style={{padding:7,border:'1px solid #8799b5'}}>✏️ Fazer ajustes</Link><button onClick={()=>submit(p)} style={{background:'#176fe3',color:'#fff',border:0,borderRadius:6}}>📤 Enviar para aprovação</button></>}</div></article>})}{!list.length&&<p style={box}>Nenhum plano nesta situação.</p>}</section>
{selected&&<section style={{...box,marginTop:20,borderTop:'5px solid #176fe3'}}><div style={{display:'flex'}}><h2>Plano de Aula: {selected.tema}</h2><button onClick={()=>setSelected(null)} style={{marginLeft:'auto'}}>Fechar</button></div><p><b>Turma:</b> {selected.turma} · <b>Disciplina:</b> {selected.disciplina} · <b>Data:</b> {new Date(selected.data).toLocaleDateString('pt-BR')}</p>{[['Objetivos',selected.objetivos],['Habilidades da BNCC',selected.habilidadesBncc],['Conteúdos',selected.conteudos],['Metodologia',selected.metodologia],['Recursos',selected.recursos],['Avaliação',selected.avaliacao],['Adaptações inclusivas',selected.adaptacoesInclusivas],['Tarefa para casa',selected.tarefaCasa],['Observações',selected.observacoes]].map(([l,v])=>v&&<div key={l}><h3>{l}</h3><p style={{whiteSpace:'pre-wrap'}}>{v}</p></div>)}</section>}</main></div>}
