import React,{useEffect,useMemo,useState}from'react';
import{Link}from'react-router-dom';
import{api}from'./services/api';
const card={background:'#fff',padding:18,borderRadius:14,boxShadow:'0 3px 15px #dce5f080'};
const input={display:'block',width:'100%',padding:9,marginTop:4,boxSizing:'border-box',border:'1px solid #b9c9df',borderRadius:7};
const colors={Atividade:'#176fe3',Prova:'#d62d4f','Avaliação':'#ef8b10',Reunião:'#7350df',Formação:'#0aa56c',Prazo:'#d16b13','Conselho de classe':'#8b3eb5',Evento:'#087ca7',Feriado:'#c93636',Outro:'#607399'};
export default function ProfessorCalendario({token}){
 const today=new Date(),year=today.getFullYear(),[month,setMonth]=useState(today.getMonth()),[events,setEvents]=useState([]),[data,setData]=useState({turmas:[]}),[students,setStudents]=useState([]),[selected,setSelected]=useState(null),[msg,setMsg]=useState(''),[error,setError]=useState('');
 const[form,setForm]=useState({turmaId:'',titulo:'',tipo:'Evento',publico:'Profissional',alunoIds:[],data:today.toISOString().slice(0,10),horaInicio:'',horaFim:'',observacao:''});
 async function load(){try{const[e,d]=await Promise.all([api.getProfessorCalendar(year,token),api.getProfessorDashboard(token)]);setEvents(e);setData(d)}catch(x){setError(x.message)}}useEffect(()=>{load()},[token,year]);
 async function chooseClass(id){setForm(v=>({...v,turmaId:id,alunoIds:[]}));setStudents([]);if(id)try{setStudents(await api.getProfessorClassStudents(id,token))}catch(x){setError(x.message)}}
 const names=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
 const cells=useMemo(()=>{const first=new Date(year,month,1),start=first.getDay(),days=new Date(year,month+1,0).getDate(),prev=new Date(year,month,0).getDate(),out=[];for(let i=0;i<42;i++){const n=i-start+1;let d,current=true;if(n<1){d=new Date(year,month-1,prev+n);current=false}else if(n>days){d=new Date(year,month+1,n-days);current=false}else d=new Date(year,month,n);const key=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');out.push({date:key,day:d.getDate(),current,events:events.filter(e=>String(e.data).slice(0,10)===key)})}return out},[events,month,year]);
 function toggleStudent(id){setForm(v=>({...v,alunoIds:v.alunoIds.includes(id)?v.alunoIds.filter(x=>x!==id):[...v.alunoIds,id]}))}
 async function save(e){e.preventDefault();setError('');setMsg('');try{await api.createProfessorCalendarEvent({...form,turmaId:form.turmaId?Number(form.turmaId):null},token);setMsg('Evento adicionado ao calendário escolar.');setForm(v=>({...v,titulo:'',horaInicio:'',horaFim:'',observacao:'',alunoIds:[]}));await load()}catch(x){setError(x.message)}}
 async function remove(ev){if(!window.confirm('Excluir o evento “'+ev.titulo+'”?'))return;try{await api.deleteProfessorCalendarEvent(ev.id,token);setSelected(null);setMsg('Evento excluído.');await load()}catch(x){setError(x.message)}}
 return <div style={{minHeight:'100vh',background:'#f4f7fc',color:'#09245a',fontFamily:'Arial'}}>
  <header style={{background:'#fff',padding:'12px 3%',display:'flex',alignItems:'center',gap:18,borderBottom:'1px solid #dce5f0'}}><img src="/images/siedu-logo-transparent.svg" alt="SIEDU — Sistema Integrado de Educação" style={{width:78,height:62,objectFit:'contain'}}/><div><b style={{fontSize:22}}>Calendário Escolar — SIEDU</b><small style={{display:'block'}}>Ano letivo {year}</small></div><Link to="/professor" style={{marginLeft:'auto'}}>← Portal do Professor</Link></header> 
  <main style={{maxWidth:1500,margin:'auto',padding:'24px 3%'}}>{msg&&<p style={{background:'#e5f7ec',color:'#16613d',padding:11}}>{msg}</p>}{error&&<p style={{background:'#fee',color:'#a22',padding:11}}>{error}</p>}
   <section style={{display:'grid',gridTemplateColumns:'minmax(700px,1fr) 360px',gap:18}}>
    <div style={card}><div style={{display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}><button onClick={()=>setMonth(m=>(m+11)%12)}>←</button><h1 style={{margin:'0 auto'}}>{names[month]} de {year}</h1><button onClick={()=>setMonth(m=>(m+1)%12)}>→</button></div><div style={{display:'flex',gap:5,flexWrap:'wrap',justifyContent:'center',margin:'14px 0'}}>{names.map((n,i)=><button key={n} onClick={()=>setMonth(i)} style={{background:i===month?'#176fe3':'#eef4fc',color:i===month?'#fff':'#09245a',border:0,padding:'7px 10px',borderRadius:7}}>{n.slice(0,3)}</button>)}</div>
     <div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',textAlign:'center',fontWeight:700}}>{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=><div key={x} style={{padding:8}}>{x}</div>)}</div>
     <div style={{display:'grid',gridTemplateColumns:'repeat(7,minmax(95px,1fr))',borderLeft:'1px solid #dce5f0',borderTop:'1px solid #dce5f0'}}>{cells.map((c,i)=><div key={i} onClick={()=>{setForm(v=>({...v,data:c.date}));if(c.events.length)setSelected(c.events[0])}} style={{minHeight:112,padding:7,borderRight:'1px solid #dce5f0',borderBottom:'1px solid #dce5f0',background:c.current?'#fff':'#f2f4f8',opacity:c.current?1:.55,cursor:'pointer'}}><b style={{display:'block',marginBottom:5,color:c.date===today.toISOString().slice(0,10)?'#fff':'#09245a',background:c.date===today.toISOString().slice(0,10)?'#176fe3':'transparent',width:25,height:25,lineHeight:'25px',borderRadius:'50%',textAlign:'center'}}>{c.day}</b>{c.events.slice(0,3).map(ev=><button key={ev.origem+ev.id} onClick={e=>{e.stopPropagation();setSelected(ev)}} style={{display:'block',width:'100%',border:0,borderLeft:'4px solid '+(colors[ev.tipo]||colors[ev.origem]),background:'#f5f8fd',fontSize:11,textAlign:'left',padding:'4px',marginBottom:3,overflow:'hidden'}}>{ev.publico&&ev.publico!=='Profissional'?'👥 ':''}{ev.horaInicio&&ev.horaInicio+' '}{ev.titulo}</button>)}{c.events.length>3&&<small>+{c.events.length-3} evento(s)</small>}</div>)}</div>
    </div>
    <aside><form onSubmit={save} style={card}><h2>➕ Adicionar evento</h2><label>Título<input required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} style={input}/></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} style={input}>{['Evento','Reunião','Prazo','Formação','Conselho de classe','Feriado','Outro'].map(x=><option key={x}>{x}</option>)}</select></label>
     <label>Público do evento<select value={form.publico} onChange={e=>{const publico=e.target.value;setForm({...form,publico,alunoIds:[],turmaId:publico==='Profissional'?'':form.turmaId});if(publico==='Profissional')setStudents([])}} style={input}><option>Profissional</option><option>Toda a turma</option><option>Alunos selecionados</option></select></label>
     <label>Data<input required type="date" min={year+'-01-01'} max={year+'-12-31'} value={form.data} onChange={e=>{setForm({...form,data:e.target.value});setMonth(new Date(e.target.value+'T12:00:00').getMonth())}} style={input}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><label>Início<input type="time" value={form.horaInicio} onChange={e=>setForm({...form,horaInicio:e.target.value})} style={input}/></label><label>Fim<input type="time" value={form.horaFim} onChange={e=>setForm({...form,horaFim:e.target.value})} style={input}/></label></div>
     {form.publico!=='Profissional'&&<label>Turma<select required value={form.turmaId} onChange={e=>chooseClass(e.target.value)} style={input}><option value="">Selecione a turma</option>{data.turmas.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select></label>}
     {form.publico==='Alunos selecionados'&&form.turmaId&&<fieldset style={{marginTop:12,border:'1px solid #b9c9df',borderRadius:8,maxHeight:190,overflow:'auto'}}><legend>Alunos participantes</legend>{!students.length&&<small>Nenhum aluno ativo encontrado.</small>}{students.map(s=><label key={s.id} style={{display:'block',padding:'5px 2px'}}><input type="checkbox" checked={form.alunoIds.includes(Number(s.id))} onChange={()=>toggleStudent(Number(s.id))}/> {s.nomeSocial||s.nome}</label>)}</fieldset>}
     <label>Observações<textarea rows="5" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})} placeholder="Pauta, local, responsáveis, materiais ou lembretes..." style={input}/></label><button style={{marginTop:12,background:'#176fe3',color:'#fff',border:0,padding:'11px 16px',borderRadius:8,fontWeight:700}}>📅 Registrar evento</button></form>
     {selected&&<article style={{...card,marginTop:14,borderTop:'5px solid '+(colors[selected.tipo]||'#176fe3')}}><small>{selected.tipo} · {new Date(String(selected.data).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR')}</small><h2>{selected.titulo}</h2><p>{selected.horaInicio?selected.horaInicio+(selected.horaFim?' às '+selected.horaFim:''): 'Dia inteiro'}</p>{selected.publico&&<p><b>Público:</b> {selected.publico}</p>}{selected.turma&&<p><b>Turma:</b> {selected.turma}</p>}{selected.publico==='Toda a turma'&&<p>👥 Todos os alunos da turma participam.</p>}{selected.publico==='Alunos selecionados'&&<div><b>Alunos participantes:</b><ul>{(selected.alunos||[]).map(n=><li key={n}>{n}</li>)}</ul></div>}{selected.disciplina&&<p><b>Disciplina:</b> {selected.disciplina}</p>}<h3>Observações</h3><p style={{whiteSpace:'pre-wrap'}}>{selected.observacao||'Nenhuma observação registrada.'}</p>{selected.origem==='Evento'&&<button onClick={()=>remove(selected)} style={{color:'#a22'}}>🗑️ Excluir evento</button>}</article>}
    </aside>
   </section>
  </main></div>
}
